### ISSUE TITLE
SEO URLs break when there are no url aliases in DB

### ISSUE THREAD

**Issue by brettwhiteman** [arastta/arastta#110]
Fresh Arastta installation, delete all rows in url_alias table. Then check the links to the information pages in the Arastta footer - they are incorrect.

**Comment by denisdulici** [comment]
Even it's an extreme case, I suppose we may use their route value in such a case.

**Comment by arumdev** [comment]
ha, it's nice to see a measured response instead of ad-hominem expletives!!!
