### ISSUE TITLE
Default layout shows up twice in list

### ISSUE THREAD

**Issue by brettwhiteman** [arastta/arastta#113]
Steps to reproduce:
1. Fresh Arastta install
2. Go to Appearance -> Layouts and delete some layouts

'Default' ends up showing twice in the list after deleting some other ones.

**Comment by cuneytsenturk** [comment]
Brett, I've fixed layout list items, can you test it?

**Comment by brettwhiteman** [comment]
Thanks - I have tested it and it's working fine now.

**Comment by cuneytsenturk** [comment]
Thanks Brett for testing
