### ISSUE TITLE
Automatic SEO URLs at categories are wrong

### ISSUE THREAD

**Issue by osworx** [arastta/arastta#118]
Arastta 1.0.8 > Categories
Leaving the field for SEO-URL empty (for automatic creation), the system is building a value, but it does not check if already existing!
For example:

Categorie = Jeans, main category = Summer > result is jeans 
but categorie cannot be saved because jeans is already used somewhere else.
The more this SEO-URL should more like summer-jeans than only jeans.

**Comment by denisdulici** [comment]
Every item (product, category etc) must have it's own URL, not affected by what it is connected with. However, from the Settings => SEO page, you can set to add the parent category to the URL while using in front-end.

**Comment by osworx** [comment]
Of course every item must have its unique url.
The problem is, that when the field is empty the system tries to generate one.
But does not check it is already exists!
So after the generation the category / product cannot be saved because the system tells the user that this SEO-URL is already in use!

The more worth when a migration is done and these URLs are already existing.
Users tend to set simple values, they do not care if it exists already and which other item has it.
They only wonder why the menus are not working because of the wrong URLs.

So what I am missing is a 'intelligent' URL-generation and maybe the hint where this value is used.
A second step should be a SEO-URL module to maintain all URLs.

**Comment by denisdulici** [comment]
I see your point Michael. As Joomla and WordPress do, we may append a numeric value if the auto-generated alias already exists: jeans-1
