### ISSUE TITLE
Refreshing modifications

### ISSUE THREAD

**Issue by osworx** [arastta/arastta#119]
After hitting the button refresh while modifications are in place and applied, following error occurs:

`Fatal error: Uncaught exception 'Symfony\Component\Filesystem\Exception\IOException' with message 'Failed to remove directory "system/modification\admin".' in system\vendor\symfony\filesystem\Symfony\Component\Filesystem\Filesystem.php:162 Stack trace: #0 system\library\filesystem.php(22): Symfony\Component\Filesystem\Filesystem->remove(Object(FilesystemIterator)) #1 system\vendor\symfony\filesystem\Symfony\Component\Filesystem\Filesystem.php(159): Filesystem->remove(Object(FilesystemIterator)) #2 system\library\filesystem.php(22): Symfony\Component\Filesystem\Filesystem->remove('...') #3 admin\controller\extension\modification.php(84): Filesystem->remove('D in system\vendor\symfony\filesystem\Symfony\Component\Filesystem\Filesystem.php on line 162`

**Comment by burakcakirel** [comment]
![modification](https://cloud.githubusercontent.com/assets/3121372/8569242/f33967d2-257d-11e5-9479-6fdad0ec0f57.png)
![modification1](https://cloud.githubusercontent.com/assets/3121372/8569241/f33673ec-257d-11e5-9540-79c4396de733.png)
