### ISSUE TITLE
Bug: localisation > geo_zones (2): getZone not defined

### ISSUE THREAD

**Issue by osworx** [arastta/arastta#124]
Calling the geo_zone page with an already saved gezone, this happens:
![geozones_referror_getzone](https://cloud.githubusercontent.com/assets/1905204/8573267/061b8714-2591-11e5-89f1-1b0db8a7db85.png)

**Comment by cuneytsenturk** [comment]
I've fixed this issue this issue (https://github.com/arastta/arastta/issues/123)
