### ISSUE TITLE
php.5.5.24 & mysqli

### ISSUE THREAD

**Issue by osworx** [arastta/arastta#127]
Using A 1.0.8 with php 5.5.24 I am getting this error while trying to establish a mysqli-connection:
`Warning: mysqli::mysqli(): (HY000/2002): No such file or directory in ../system/library/db/mysqli.php on line 16`

`Notice: Error: Could not make a database link (2002) No such file or directory in ..system/library/db/mysqli.php on line 19`

**Comment by denisdulici** [comment]
It seems to be an issue with namespaces. Going to test and report back.

**Comment by denisdulici** [comment]
I just tried XAMPP for Windows PHP 5.5.27 with both Arastta 1.0.8 and 1.1 and it worked fine for both:
https://www.apachefriends.org/download.html

![2015-08-02_0202](https://cloud.githubusercontent.com/assets/5254835/9023949/45829932-38bb-11e5-8a73-b1b3269f4c97.png)

Where do you exactly get this error?

**Comment by osworx** [comment]
With the latest version of XAMPP it works fine.
But with php 5.5.24 as mentioned in the 1st post, I recieve this error.
We have this php-version on one of our servers.

**Comment by denisdulici** [comment]
I tested Arastta 1.0.8 with PHP 5.5.24 and works fine too:
http://sourceforge.net/projects/xampp/files/XAMPP%20Windows/5.5.24

I also checked the PHP changelog and there is no change related with namespaces, between 24 and 27.
