### ISSUE TITLE
Changing core elements - cache should be deleted

### ISSUE THREAD

**Issue by osworx** [arastta/arastta#132]
If values of core elements are changed (e.g. text for weight, lengths etc.) the cached files are still exist.
Therefore these old values are displayed instead of the new.
So, whenever settings like that are changed, the cache should be also cleaned.

If not done, that might confuse some - and I am sure they will post a bug.

**Comment by denisdulici** [comment]
Michael, are you using the Page Cache? Have you enabled the "Clear After Save" from Settings => Cache tab?

**Comment by osworx** [comment]
No, no cache is used (as always during development).

**Comment by denisdulici** [comment]
Have you enabled the "Clear After Save" from Settings => Cache tab? If not, can you enable it and try again?

**Comment by osworx** [comment]
Yes, is always enabled.

**Comment by cuneytsenturk** [comment]
[fixed clear cache issue](https://github.com/arastta/arastta/commit/4c321c1cd7c6b93ffcee3d5d42d0c67f9bc63315)
