### ISSUE TITLE
Problem with EmailTemplate

### ISSUE THREAD

**Issue by valdeir2000** [arastta/arastta#140]
Hello,

Have you thought about deleting the library EmailTemplate and use a model for this? Becomes much easier to use and in case of problems is easier to fix .. Currently this library is quite confusing and very, very big.

![01](https://cloud.githubusercontent.com/assets/606481/8643673/65a7222c-290d-11e5-8b64-fc9f79209070.PNG)
Request URL:http://localhost/arastta-github/arastta/admin/index.php?route=sale/order/api&token=XXX&api=api/order/history&order_id=1
Request Method:POST
Status Code:500 Internal Server Error

**Comment by denisdulici** [comment]
The purpose of Email Template is to prepare the email content to be used by the core and 3rd parties, in catalog and admin side. Refactoring the library can be done only within a major release.

As for the issue, I can see such a possibility when you use another language but English and have not entered the email data for that language. We must copy those from English after language installation, as we do for other parts such as products, menus etc.

**Comment by cuneytsenturk** [comment]
valdeir2000 - Could you test the email subject issue.
