### ISSUE TITLE
Dates, days and months only in English format

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#142]
We have discussed some about the server locale earlier (nb-NO.utf8 etc), and I suspect this being related, combined with the system not using date formats from language files "all over".

There is several places in Arastta displaying English date format (not using define from language file?).

Like in the Dashboard Stats, displaying "July 1, 2015 - July 15, 2015" when it should be "1. Juli 2015 - 15. Juli 2015", and the drop-down also displays English texts.
![arastta_dashboard](https://cloud.githubusercontent.com/assets/858132/8695887/e3182cf8-2af0-11e5-887c-1942a2209cd2.png)

In the calendars (date picker) the month and days are displayed in English (server locale issue?), and the date in English format.
![arastta_product_edit_date](https://cloud.githubusercontent.com/assets/858132/8695892/e6296dbc-2af0-11e5-8c21-18e94b9df049.png)

**Comment by denisdulici** [comment]
It's not related with server but JS date picker locale:
http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#locale

The current momentjs is only in English:
http://momentjs.com
https://github.com/arastta/arastta/tree/master/admin/view/javascript/jquery/datetimepicker
https://github.com/arastta/arastta/tree/master/admin/view/javascript/jquery/daterangepicker

Assinging this to 1.1 milestone.

Thanks for reporting :smirk:

**Comment by osworx** [comment]
For the datepicker displaying in locale, I have already an OCMod.

**Comment by syntaxerror** [comment]
Is the display of dates bellow the stats (first picture) etc. also related to date picker?
Should display as 01.07.2015 (or better 1.7.2015) for Norwegian, not as it does now with 2015-07-01

Great Michael, feel free to upload a patch for it. ;)

**Comment by osworx** [comment]
I have made this mod in March this year.
Covers only the input fields, but currently not the overview (my focus was on other things the last weeks).
I assume, that the datepicker and the select fields are 2 different pair of shoes ..

**Comment by denisdulici** [comment]
Yes Rune:
https://github.com/arastta/arastta/blob/master/admin/view/template/dashboard/charts.tpl#L67

Thanks Michael for the patch :smirk:

**Comment by denisdulici** [comment]
The following date format has not been changed as it requires filter during save in db: http://screencast.com/t/SWN83jRE

Will handle this later.
