### ISSUE TITLE
Admin Login > Language Selection

### ISSUE THREAD

**Issue by osworx** [arastta/arastta#143]
A 1.0.8: text of select field for language is partly hidden (approx. 40 px too left):
![admin_login_language_selection](https://cloud.githubusercontent.com/assets/1905204/8699271/ae7010b0-2b04-11e5-9b3e-f70507855bac.png)

**Comment by cuneytsenturk** [comment]
![admin-login](https://cloud.githubusercontent.com/assets/10936547/8701269/71998b20-2b19-11e5-83d2-0f9fe2e85d7c.png)

**Comment by cuneytsenturk** [comment]
![adminloginform](https://cloud.githubusercontent.com/assets/10936547/8701746/5609999c-2b1c-11e5-9fe1-b9a544f7dd86.png)
