### ISSUE TITLE
Emailtemplates in other languge then EN not to save

### ISSUE THREAD

**Issue by osworx** [arastta/arastta#146]
Editing email templates in another language then english is not possible.
Wether the subject not the text can be saved.
But the message says: Successfully saved (or something else ..).

Both buttons (Save & Save & Close) are not working.

**Comment by osworx** [comment]
Okay, see that this has been already fixed.
Because this is an important issue, the next version should be published asap.

**Comment by denisdulici** [comment]
Michael, can you please apply the fix manually as 1.0 is locked due to the soon release of 1.1?
