### ISSUE TITLE
EmailTemplate does not work when register new "Order Status"

### ISSUE THREAD

**Issue by valdeir2000** [arastta/arastta#149]
This EmailTemplate system is complicated and boring to work.

I added a form to create new templates, but it is very complicated for the inexperienced user.

![01](https://cloud.githubusercontent.com/assets/606481/9020633/8339951e-37ee-11e5-8a94-9e464c9a0c7b.PNG)

![02](https://cloud.githubusercontent.com/assets/606481/9020639/f10253d8-37ee-11e5-845d-577faadc8d36.PNG)

![03](https://cloud.githubusercontent.com/assets/606481/9020634/835750ea-37ee-11e5-941e-9fbbd716af45.PNG)

**Comment by denisdulici** [comment]
The problem is that the Description field of the email template created automatically for that new order status is empty.

The solution is to use the content as within default order statuses when creating the email template.

**Comment by valdeir2000** [comment]
I made that ugly hack and apparently resolved.
http://pastebin.com/sH7xKVsq

I found this other problem. When the column "name" is empty it tries to capture a default value, but the method getDefautOrderSubject() does not exist (Line 736 and 745; Library EmailTemplate)

![01](https://cloud.githubusercontent.com/assets/606481/9023705/5885cfec-387d-11e5-83f8-e9d61cdc51f5.PNG)

**Comment by denisdulici** [comment]
Hmm.. You're right, these issues seems to be caused by the non-existent getDefaultXyz functions:
https://github.com/arastta/arastta/blob/master/system/library/emailtemplate.php#L719

Will leave this to @cuneytsenturk for further review as he has designed the email template system.

**Comment by cuneytsenturk** [comment]
Hi Valdimer,

I've added default order mail subject & content then create new order status add other order status  same mail content.

Can you test this solution?

**Comment by valdeir2000** [comment]
I not tested because they said that would be different.
