### ISSUE TITLE
1.1.0rc1 > Checkout not possible when SEO is enabled

### ISSUE THREAD

**Issue by osworx** [arastta/arastta#170]
Fresh install, default settings, German as language, all SEO settings enabled.
Calling the shop works, adding a product also.
But clicking on the checkout link, open that page and leads to an server error 404:
`../de/checkout/cart.html`

Disabling following setting and checkout works:
`Remove index.php > No`

**Comment by denisdulici** [comment]
Applied the same steps and it works fine for me Michael:
![2015-08-12_1908](https://cloud.githubusercontent.com/assets/5254835/9229409/ab918b76-4125-11e5-9648-31c591f514c9.png)

**Comment by osworx** [comment]
Sorry, my own fault .. forgot to enable the .htaccess.
Guess this may happen to others too .. maybe a notice (popup) when enabling / changing the settings which need a .htaccess ?

**Comment by denisdulici** [comment]
Ah, glad to see it works for you too ;) As for the popup, must discuss it within the development team first.
