### ISSUE TITLE
1.1.0rc1 > PDF-Invoice not possible

### ISSUE THREAD

**Issue by osworx** [arastta/arastta#171]
After clicking on the button to create a PDF-Invoice (no invoice number already created), following error occurs:
`Notice: Undefined offset: 16 in ..\system\mpdf\mpdf.php on line 21162
Notice: Undefined offset: 1 in ..\system\mpdf\mpdf.php on line 21193
Warning: Cannot modify header information - headers already sent by (output started at ..\system\library\app.php:86) in ..\system\mpdf\mpdf.php on line 8314
Warning: Cannot modify header information - headers already sent by (output started at ..\system\library\app.php:86) in ..\system\mpdf\mpdf.php on line 1706 mPDF error: Some data has already been output to browser, can't send PDF file`
The header errors are okay, came from the display of errors - but the offset 16 & 1

**Comment by denisdulici** [comment]
That is a bug of mPDF https://github.com/mpdf/mpdf

It works fine with errors disabled.

**Comment by osworx** [comment]
Comment this again: the bug still exists (Arastta 1.1.2).

From my point of view, disabling the error_reporting requires the knowledge where (in which file).
And I do NOT want to encourage any enduser to edit sensible files, here the startup.php.
So, this means this bug has to be solved asap - no matter if mpdf or arastta is doing that.
That is one of the risks when embedding 3PD libraries.

Opened an issue there: https://github.com/mpdf/mpdf/issues/46
