### ISSUE TITLE
1.1.0rc1 > Backend creating new customer = no country selection

### ISSUE THREAD

**Issue by osworx** [arastta/arastta#174]
When creating a new customer via the backend and if the country is forgotten, after hitting the save buttons it is not possible to select the missing country (again) and therefore all data have to set again.

The jquery call is correct and done, values are returned, but not assigned to the select field.

![11rc_1_missing_country_selection](https://cloud.githubusercontent.com/assets/1905204/9230857/1f2b0414-4125-11e5-867c-24642976ca60.png)

**Comment by denisdulici** [comment]
Confirmed, thanks Michael :smirk:
