### ISSUE TITLE
Options 'Out Of Stock' is hidden

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#187]
'Out Of Stock' Options is hidden on product display, even if 'Stock Checkout' is 'Yes'

~~Btw! I think it would be better to have a options to hide or display on 'Out Of Stock', for both products and options, but hide buy button instead. Options could be "greyed out" instead of hidden.~~

**Comment by denisdulici** [comment]
I'm not sure I got this Rune :cry: A screenshot may help?

**Comment by syntaxerror** [comment]
System -> Settings -> Option -> Stock:
![system_settings_option](https://cloud.githubusercontent.com/assets/858132/9628359/050198c4-5173-11e5-9961-632cab9af90e.png)

Product edit, zero stock on option 2:
![product_edit](https://cloud.githubusercontent.com/assets/858132/9628396/3b1b821c-5173-11e5-998a-a9185a1257ac.png)

Product display in store, option 2 with zero stock missing from display:
![product_display](https://cloud.githubusercontent.com/assets/858132/9628434/76e64a20-5173-11e5-944f-ba706771043e.png)

**Comment by syntaxerror** [comment]
~~For products when 'Stock Checkout' is 'No' you still can click the 'Buy' button, and don't get notified about restrictions for checkout before you're in cart - which is annoying for the customer ...~~

~~Anyhow some store owners would instead like to hide the 'Buy' button (like Zen Cart etc can do) or display a 'Notify me' (VirtueMart), and 'grey out' options like quite many of the option extensions for OC can do.~~

**Comment by denisdulici** [comment]
OK, got it. This is a known issue that comes from OC and should be considered within the Options improvements http://arastta.org/ideas/idea/5

**Comment by syntaxerror** [comment]
Maybe it could and should be fixed for normal products without options as a start.

**Comment by syntaxerror** [comment]
PR: Allowing Pre-Order on options #681
