### ISSUE TITLE
Adding new administrator - Auto create password

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#188]
When a new administrator user is added from the admin interface, it would be nice if the password was auto created and mailed to the user, like in Joomla.

For security, the user should change it anyway on first login.

**Comment by BrettMW** [comment]
What's the advantage of this over the current setup (i.e. setting the password during installation)? Personally I find it very annoying to have to go fetch the password from my email then have to change it straight away anyway.

**Comment by syntaxerror** [comment]
I'm closing this and adding it to ideas section instead:
https://arastta.org/component/mijovoice/idea/49-adding-new-administrator-auto-create-password
