### ISSUE TITLE
Styling on Stock Status

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#192]
Was thinking that it would be nice to have styling on the stock statuses, to make them more visible- t.ex. red text on 'Sold out'.

Either as a styling class for each or just a simple colour select for the text display.

**Comment by syntaxerror** [comment]
Before:
![arastta_stock_display](https://cloud.githubusercontent.com/assets/858132/9728770/f66f397a-5612-11e5-9727-ec821da35675.png)

After:
![arastta_stock_display_styled](https://cloud.githubusercontent.com/assets/858132/9728765/f2eed8a0-5612-11e5-98d7-340f9702a824.png)

**Comment by denisdulici** [comment]
Nice idea. Adding a color selection in admin stock status add/edit page would be the best solution. What do you think?

**Comment by sunsys0** [comment]
+1

**Comment by syntaxerror** [comment]
+1 for colour selection

**Comment by osworx** [comment]
+1 but also the possibility to add an image indicating 'On Stock > Green', 'Preordered (or low) > Yellow' and 'Out of Stock > Red',
Simpliest solution would be to let the admin define what he wants: text & colorpicker.
