### ISSUE TITLE
1.1.1 Fresh Install > No Language Settings

### ISSUE THREAD

**Issue by osworx** [arastta/arastta#195]
As title says, below screenshots (installed already a 2nd language):
![missing_language_settings_fresh_install](https://cloud.githubusercontent.com/assets/1905204/9767044/77761502-571c-11e5-85f9-33f13d61c20a.png)
![missing_language_settings_fresh_install_2](https://cloud.githubusercontent.com/assets/1905204/9767049/7a39bb0e-571c-11e5-9bd2-fefe2a3cbc2e.png)

**Comment by cuneytsenturk** [comment]
I just tried a clean installation with 1.1.2 and it worked fine, same after installing a 2nd language.
![language](https://cloud.githubusercontent.com/assets/10936547/9871438/52cb16a6-5b9c-11e5-82e0-4038b33c1582.png)

**Comment by osworx** [comment]
Maybe with 1.1.2 something has changed .. have to try with 1.1.2 and will report.

**Comment by osworx** [comment]
Works with 1.1.2 > can be closed.
