### ISSUE TITLE
PHP 5.3.29 - Update fails

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#224]
I have noticed the update fails on cPanel servers running PHP 5.3.29, if other PHP versions is selected for the folder hosting Arastta it works fine.

The update process is just running for a while, before telling the update was fine, but still showing the old version in footer and telling a new version being available.

PHP 5.3 is really outdated, so maybe it's OK to just rise the system requirements to PHP 5.4, in stead of wasting time on PHP 5.3 issues. Anyhow, tell me if you need any more systeminfo.

**Comment by syntaxerror** [comment]
Who cares... let's just use PHP 5.4 or newer.

**Comment by denisdulici** [comment]
Rune, I agree that PHP 5.3 is very outdated but it's still used by a large percent:
http://w3techs.com/technologies/details/pl-php/5/all
https://wordpress.org/about/stats

**Comment by syntaxerror** [comment]
Yeah, but this issue has been posted in October. Didn't seem like anyone cared, and I'm personally not going to spend a lot of time debugging or re-coding it. Thus I decided to close it.

**Comment by denisdulici** [comment]
I'll try to create a local PHP 5.3 environment and test it asap.
