### ISSUE TITLE
Breadcrumbs - Wrong display order for categories

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#228]
Ref http://arastta.org/forum/breadcrumb-order

The breadcrumb is expected to display: Tablets & eBook Readers > test 20 > test 25
But instead it's displaying: test 20 > Tablets & eBook Readers > test 25

![breadcrumbs_ordering](https://cloud.githubusercontent.com/assets/858132/10642319/c4578476-7825-11e5-9d6f-70e7937ee90b.png)

**Comment by stlewis59** [comment]
This appears to be in ...\catalog\controller\product\category.php - around line 84

**Comment by syntaxerror** [comment]
Actually it's related to SEO. If SEO is deactivated, the breadcrumbs are fine.
Also noticed in one test install, with 3 category levels, that the URL was messed up the same way.

**Comment by cuneytsenturk** [comment]
![frontend-breadcrumbs-issue-solve](https://cloud.githubusercontent.com/assets/10936547/10687601/e89c29d4-7976-11e5-88fd-bd3c70505511.png)
