### ISSUE TITLE
SMTP Password is visible

### ISSUE THREAD

**Issue by denisdulici** [arastta/arastta#242]
![2015-11-04_1206](https://cloud.githubusercontent.com/assets/5254835/10933840/12519bb2-82e4-11e5-8ec6-fe4cf31e0757.png)

**Comment by osworx** [comment]
Not sure what for this change should be good??
If the settings shall not be visible for others than the admin, a simple change for the permission will do the job.
Personally I like to see the value of the field - I have to maintain unlimited shops and with that change I am not able now to see what is the value!

**Comment by denisdulici** [comment]
It is good for security. Admin may not be the admin itself but a hacker and they must not be able to access emails.

It's true that security measures bring difficulty at every part of our life.
