### ISSUE TITLE
Admin breakages with HTTPS

### ISSUE THREAD

**Issue by LinuxJedi** [arastta/arastta#288]
Customizer in particular is completely broken when HTTPS is enabled. In particular:
- $data['icon'] uses HTTP_CATALOG so has an http:// URL
- $data['frontend'] uses HTTP_CATALOG so has an http:// URL
- $data['backend'] uses HTTP_SERVER so has an http:// URL

Both Firefox and Chrome break on the JS because there are insecure elements on the page. In all these cases I have fixed with this simple hack:

```
($this->request->server['HTTPS']) ? HTTPS_CATALOG : HTTP_CATALOG 
```

(obviously changing to HTTPS_SERVER/HTTP_SERVER for backend).

I believe there are other places that are also broken, especially with the favicon but I haven't looked through it all yet.

**Comment by LinuxJedi** [comment]
marketplace.tpl and admin/common/header.php also affected

**Comment by LinuxJedi** [comment]
(note that it is easy to test this with Let's Encrypt if you don't have proper signed SSL certs)

**Comment by cuneytsenturk** [comment]
Hi Andrew,

I have added all path HTTPS. Thank you for your attention.
