### ISSUE TITLE
File manager not working in version 1.2

### ISSUE THREAD

**Issue by opencartpm** [arastta/arastta#310]
$this->response->setOutput($this->load->view('tool/file_manager.tpl', $data));

"admin\view\theme\basic\template\tool\file_manager.tpl"
not found here
Please add

**Comment by cuneytsenturk** [comment]
Arastta basic mode same use advanced mode view for file manager feature,

so then not necessary basic mode this file "admin\view\theme\basic\template\tool\file_manager.tpl".

Already it works. You can watch this video : http://screencast.com/t/0YNJtvWh8i

Did you test it?
