### ISSUE TITLE
Feature: Per-option reward points

### ISSUE THREAD

**Issue by LinuxJedi** [arastta/arastta#311]
At the moment you can only set the amount of additional reward points per option for spending points. Not the amount of additional points received when purchasing a given option. This is not good if the options are significantly different in price.

I've attached a patch of how I've hacked this onto a 1.2 installation. This is not a complete/universal implementation but should be "good enough" to get started. The patch required the additional DB columns:

```
alter table ebz_product_option_value add column points_added int(8) NOT NULL;
alter table ebz_product_option_value add column points_added_prefix varchar(1) NOT NULL;
```

[rewards.diff.txt](https://github.com/arastta/arastta/files/69838/rewards.diff.txt)

**Comment by LinuxJedi** [comment]
warnings: I missed two quote marks in the SQL query building in admin/model/catalog/product.php

**Comment by cuneytsenturk** [comment]
An extension which includes this feature will be added to the Marketplace as soon as possible:
https://github.com/arastta/addons/issues/35
