### ISSUE TITLE
Rename robots.txt 

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#336]
robots.txt needs to be renamed into robots.txt.dist else it's overwriting any customisations made (replacing the file) when updating.

**Comment by syntaxerror** [comment]
Closing. Discussed in PR: https://github.com/arastta/arastta/pull/384

**Comment by syntaxerror** [comment]
Reopening as PR got closed.
See discussion in #384 and feel free to continue it here then.

**Comment by denisdulici** [comment]
Fixed here https://github.com/arastta/arastta/pull/526
