### ISSUE TITLE
Can't save user

### ISSUE THREAD

**Issue by Zemistr** [arastta/arastta#362]
When I try to save my own account, I see multiple errors.

Try it on url "/admin/index.php?route=user/user/edit&token=xyz&user_id=1".
Just click on save button.

**Comment by cuneytsenturk** [comment]
Hi @Zemistr 

Firstly, I have checked default package and it can save and modified user. I can't see any issue.

You can use https://arastta.org/forum/ and ask a question here => https://arastta.org/forum/ask

Please ask a question on Arastta From page.

Also I hopefully, You fill this fields.

![user-page](https://cloud.githubusercontent.com/assets/10936547/13431710/266576f4-dfd3-11e5-8f4b-ace4f2b014a6.png)

**Comment by Zemistr** [comment]
Hmm...I don't see the fields below Theme... :/

**Comment by Zemistr** [comment]
I have v1.2.7

**Comment by cuneytsenturk** [comment]
Okey I understand your issue.

You use Display error => advanced and User detail page show same this

![error-report](https://cloud.githubusercontent.com/assets/10936547/13432195/4bddead6-dfd5-11e5-911d-f6ba1f2e3d78.png)

if you want to quick solution, You can change Display error status (Basic)  then use it.

![display-error](https://cloud.githubusercontent.com/assets/10936547/13432123/fa35a4a8-dfd4-11e5-9274-ee6437d97072.png)

Already I am working on User page and solve this issue but not commit yet.

**Comment by Zemistr** [comment]
Thank you very much, it is enough for now. :)
