### ISSUE TITLE
Print Invoice displays 'Invoice + order id' as title

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#383]
Print Invoice displays 'Invoice + order id' as title, not the invoice number, and it's no good.

Ref line: https://github.com/arastta/arastta/blob/1.3-dev/admin/view/template/sale/order_invoice.tpl#L17

Since this isn't really a real invoice, I'm not sure what the best option would be. Normally I would name it a "Proforma Invoice", so I'm thinking about a header like "Proforma Invoice - Order ID xxxx", **since it can be printed before a invoice number is generated**.

> A proforma invoice is not a true invoice – it is simply a document that declares the seller's commitment to provide the goods or services specified to the buyer at certain prices. Proforma invoices are not recorded as an accounts receivable by the seller nor are they recorded as an accounts payable by the buyer.

I'll make a PR, including new language string if needed, as soon as we agree on something.

**Comment by denisdulici** [comment]
That is how the precursor of Arastta used to use it, the Download PDF Invoice one is a real invoice, in front and back end:
https://github.com/arastta/arastta/blob/master/catalog/view/theme/default/template/account/order_invoice.tpl

Why not replace the order id with invoice number? Or maybe use the PDF output for print too?

**Comment by syntaxerror** [comment]
Well, but it's not a real invoice in most countries under different regulations as it is. What the precursor of Arastta isn't anything we should care about, as it's mostly just a weir system built in China, but the button and the print page is still there ...

And you can't replace it with a non existing invoice number. You can print this without generating it first, even for cancelled orders etc.: https://github.com/arastta/arastta/blob/1.3-dev/admin/view/template/sale/order_invoice.tpl#L37-L39

Anyhow, using the PDF output for print of a real invoice is surely a better way. Removing the old print option completely. Unless someone need the "Proforma Invoice" option, as some might now and then.

**Comment by syntaxerror** [comment]
Closing as PR has been added.
