### ISSUE TITLE
PDF Invoice button opens blank page

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#385]
On migrated systems where there isn't a PDF Invoice available, or non-migrated when a invoice number isn't generated yet, the PDF Invoice button will just go to a blank page with a URL like /index.php?route=sale/order/invoicepdf&token=...order_id=xxxx

Maybe it's better to display a popup with some info about missing PDF's?

For migrated systems, or older orders from before the PDF invoice system was added, it would be great if the missing PDF was generated when button was clicked (or generation run in invoice list). Meaning a possibility to generate a PDF Invoice for all orders where a invoice number exists, but PDF is missing.

_Side note: Anyhow it should be easier to generate the invoice numbers, t.ex. make it happen automatically when the order is marked delivered._

**Comment by denisdulici** [comment]
You're right, we should disable the invoice buttons if the invoice number isn't generated yet.

As for generating invoice numbers, there is such a button at the top right of Sales => Invoices page.

**Comment by syntaxerror** [comment]
> As for generating invoice numbers, there is such a button at the top right of Sales => Invoices page.

True, but it's actually a weird function, generating a invoice number for all at once without any choices. I don't get it as it's not normal for a invoicing program to do it that way. Anyhow, it's probably better to post about this in the forum, or at least keep it as a separated issue - my mistake. :)

**Comment by syntaxerror** [comment]
> You're right, we should disable the invoice buttons if the invoice number isn't generated yet.

What about it triggers a popup telling the invoice isn't generated yet, asking if you want it to do it now if it has the correct set status for allowing invoice generation, else tell the required status isn't reached?

**Comment by denisdulici** [comment]
Invoices are generated based on your filters so you can filter order statuses, customers etc. As for the popup, we must discuss it first within the development team. I just sent a quick fix that will enable/disable the button based on the invoice number.
