### ISSUE TITLE
Display parent category during category selection

### ISSUE THREAD

**Issue by EnesErtugrul** [arastta/arastta#394]
It's confusing to choose the sub-category if you have sub-categories with the same name. Display the parent category (just like Arastta's menu category selection) during the category selection for the product.

![img-20160330-wa0005](https://cloud.githubusercontent.com/assets/7959294/14169922/462447c8-f733-11e5-8dd5-8faf79b5ea6f.jpg)
![img-20160330-wa0006](https://cloud.githubusercontent.com/assets/7959294/14169923/462632d6-f733-11e5-92cc-626aed76b190.jpg)

**Comment by dibidib** [comment]
i follow..

**Comment by cuneytsenturk** [comment]
Product detail page category added;
![category-name](https://cloud.githubusercontent.com/assets/10936547/14174678/35c3bff4-f746-11e5-937c-1256a64e6251.png)
