### ISSUE TITLE
Rounding of sale in dashboard widget is overridden

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#429]
The sale amount displayed in dashboard widget is supposed to be rounded according to those lines: https://github.com/arastta/arastta/blob/master/admin/controller/dashboard/sale.php#L35-L45

But is overridden by the following line: https://github.com/arastta/arastta/blob/master/admin/controller/dashboard/sale.php#L47

![dashboard_sale_before](https://cloud.githubusercontent.com/assets/858132/14791381/5521e5ec-0b1e-11e6-9c15-02b37a6d65fc.png)

**Comment by denisdulici** [comment]
Thanks Rune.

**Comment by syntaxerror** [comment]
I'm not sure about this whole currency "layer" here, it makes some more issues in some currencies, like the Nordic ones (SEK, NOK, DKK etc.).

Dot is the thousand separator, and comma is decimal separator. This is working fine, but shops often uses zero decimals, and instead use ",-" as "Symbol Right".

This will then lead to this weird display in the widget:
![dashboard_sales_widget](https://cloud.githubusercontent.com/assets/858132/14863774/c6df91e6-0cbf-11e6-97e5-b980b8923e3b.png)

Maybe it's better to just add the currency symbol, or find a way to strip out the symbol right?

Btw! A big K etc would also not be correct. At least in Norway a single quote would probably be the more correct "sign" for thousand. T.ex. Kr. 10.000,- = Kr. 10' (but k can also be used and is possibly wider understood by people, but then it should be small, as in 10k)

Not very important, but still ... :)

**Comment by syntaxerror** [comment]
Related, issues with other currency displays too: https://arastta.org/forum/dashboard-sales-incorrect

**Comment by syntaxerror** [comment]
What do you think about doing this instead:
`$data['total'] = $this->config->get('config_currency') . ' ' . $this->currency->format($data['total'], $this->config->get('config_currency'), '', false) . $suffix;`

Then we get this display for NOK:
![sales_dash_widget_nok](https://cloud.githubusercontent.com/assets/858132/15012012/dbd2b202-11fd-11e6-9909-0308a39aa72d.png)

And EUR in multistore:
![sales_dash_widget_eur](https://cloud.githubusercontent.com/assets/858132/15012021/eabe1d38-11fd-11e6-8a93-0facd7b6ba93.png)

Btw! It seems like uppercase K is used for currency, while lowercase is for metrics, at least in English - so we can leave it as it is. Not so important for the Nordic countries alone, that it's worth making lots of changes in this.
