### ISSUE TITLE
Email Template - Customer Credit - Short code missing

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#448]
In the Email Template - Customer Credit, the short code for credit and credit total is missing.

![email_template_credit](https://cloud.githubusercontent.com/assets/858132/14997305/c68aa02a-1186-11e6-9498-37433153f650.png)

**Comment by Gh0stSnipu** [comment]
This problem still presist...
I mean that when sending credit email it shows full html code and text is messed up.

**Comment by syntaxerror** [comment]
> This problem still presist...
> I mean that when sending credit email it shows full html code and text is messed up.

That is not related at all. So NO, it surely does not "presist" or persist.
