### ISSUE TITLE
Customizer - Needs to support more color values

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#453]
If you try to change the colors of t.ex the new Second theme, you'll soon notice it's impossible to change all "gold" fonts, without also using custom.css - even if advanced is selected.

**Comment by cuneytsenturk** [comment]
Added new colors =>  https://github.com/arastta/arastta/commit/db062cd383b6a8c361183ddcb58e11386149d8bd | https://github.com/arastta/arastta/commit/988bae2e2b4433ad7f93aa785a8e397ac10ff6ab | https://github.com/arastta/arastta/commit/3556ff980a0837da25b68f445fc24fbd952f605f
