### ISSUE TITLE
Appearance -> Layout - Save button doesn't work properly

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#458]
In "Appearance -> Layout" the "Save" button doesn't work properly when a new module is added, it' still blurred and can't be pushed.

You have to move the module to another position first (then back), to be able to save the layout.

![no_module_save](https://cloud.githubusercontent.com/assets/858132/15041838/d5e50244-12c7-11e6-9d76-590704a50eea.png)

![module_save](https://cloud.githubusercontent.com/assets/858132/15041818/acb5f964-12c7-11e6-8a11-bc81665d4a41.png)

Btw! Tested in Vivaldi and Firefox.

**Comment by denisdulici** [comment]
You're late Rune :wink:  https://github.com/arastta/arastta/issues/455

**Comment by syntaxerror** [comment]
Nothing better than that :)
