### ISSUE TITLE
Side category module not showing child categories

### ISSUE THREAD

**Issue by fullstackfool** [arastta/arastta#460]
From what i can see with two separate installs the side category module doesn't show the child categories properly. In catalog/controller/module/category.php lines 21/22 and 27/28 point to $parts[0] and $parts[1] respectively, but dumping parts shows an empty value at the zero index, requiring each reference at those line to be incremented by 1, or the blank "master category" to be removed if it's not needed.

**Comment by syntaxerror** [comment]
Works in my installs.

What version of Arastta and PHP etc., and template, are you using?

![side_cats](https://cloud.githubusercontent.com/assets/858132/15275618/25e7871c-1ad9-11e6-9d3f-e88b156a9b28.png)

Note! Only 2 levels supported by default, parent and child.

**Comment by syntaxerror** [comment]
Seems like I can confirm there is a issue on a fresh install of Arastta 1.3 on PHP 5.5.30
Weirdly it works for updated sites though ...

In this site, the second level categories are listed as "parents / top levels" in the category module
![category_mess](https://cloud.githubusercontent.com/assets/858132/15300711/bc1ea29a-1bb2-11e6-94de-e3a194e5d881.png)

**Comment by fullstackfool** [comment]
Apologies for the lack of response, been a bit ill.

Server running on 5.5.9 PHP at the moment, and the Arastta version is 1.3.

I received a notification regarding a response of yours, highlighting a possible issue you found where child categories were being treated as top level in the module. This wasn't the case in my issue, the children simply wouldn't show.

Dumping $path from line 16

`var_dump((string)$this->request->get['path']);`

gives 0_65 for instance. There is no category zero in the db, so i'm not sure what this is being used for, but it is this leading 0 which causes the issue for me.

**Comment by syntaxerror** [comment]
Forget about the notification please, was just me being third and having a cache issue. ;)

Your PHP version is really outdated (latest PHP 5.5 is 5.5.35), but I don't think that is the issue, but you should update it anyway (or move hosting). Anyhow you should at least get Arastta updated to 1.3.2.

Childs still displays fine for me, so I have no idea about your issue.

**Comment by fullstackfool** [comment]
Yeah i'm aware of how outdated the php version is, one item on a long list of issue to be fixed i can assure you. 

Thank you for attempting to replicate. As long as it's not a fundamental issue in Arastta we can consider this done.
