### ISSUE TITLE
Order mail - Order totals with random ordering

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#469]
In a fresh install of Arastta 1.3.1 the order totals is displayed with reversed ordering in the mails, in spite they are displaying with correct ordering in cart/checkout and admin ...

**Comment by syntaxerror** [comment]
I have not been able to recreate this after updating to 1.3.2, so I'm closing it for now.

**Comment by syntaxerror** [comment]
The issue is still there, but they are not reversed, they are actually random - thus I got fooled.

![random_totals_mail1](https://cloud.githubusercontent.com/assets/858132/15775702/0edc78c2-298c-11e6-94e7-de6d2afa3ad3.png)

![random_totals_mail2](https://cloud.githubusercontent.com/assets/858132/15775705/12bb08a0-298c-11e6-8971-1151e3855616.png)

**Comment by gepeixoto** [comment]
In system/library/emailtemplate.php, function getTotalTemplate, we need to sort the total array before the foreach:

```
$sort_order = array();

foreach ($getTotal as $key => $value) {
    $sort_order[$key] = $value['sort_order'];
}

array_multisort($sort_order, SORT_ASC, $getTotal);
```

**Comment by syntaxerror** [comment]
Could you add a PR for this please, or at least full code change description?

**Comment by gepeixoto** [comment]
I'm facing issues with git and can't do a PR, so here is the entire function:

```
public function getTotalTemplate($getTotal, $template_total, $order_info) {
    $result = array();

    // Sort
    $sort_order = array();

    foreach ($getTotal as $key => $value) {
      $sort_order[$key] = $value['sort_order'];
    }

    array_multisort($sort_order, SORT_ASC, $getTotal);

    foreach ($getTotal as $total) {
      // Replace Product Short Code to Values
      $total_find = $this->getTotalFind();
      $total_replace = $this->getTotalReplace($total, $order_info);

      $result[] = trim(str_replace($total_find, $total_replace, $template_total[1]));
    }

    return $result;
  }
```

**Comment by syntaxerror** [comment]
Thanks, I tested it and it works fine.
I'll make a PR for it then.
