### ISSUE TITLE
Admin - Edit Categories with & in name

### ISSUE THREAD

**Issue by stlewis59** [arastta/arastta#481]
Categories with '&' in the name are saved as '&amp;' but cannot then be edited.

**Comment by stlewis59** [comment]
And the same for Product names.... As an example www.jasmine-records.co.uk/store/index.php/category-229/product-282

**Comment by syntaxerror** [comment]
I tested adding a category with ampersand in the name, and I see no problem saving it, and no problem editing it. I tested it in both advanced and basic admin theme, on Arastta 1.5.5

Maybe you should add some more info about this. Your version of Arastta, basic system information. And also a more informative description of what "cannot be edited" actually means - what do you see / what is happening?

**Comment by stlewis59** [comment]
Rune

 

Thanks. This was raised so long ago that it has probably been fixed at some point!

 

 

Regards,

Simon Tyrrell-Lewis
___________________________________________________________________
Tyrrell-Lewis Associates

2 Aldermary Road, Bromley, Kent BR1 3PH, UK

Phone:  +44 (0)20 8290 1488

Mobile: 07940 636564

Email: simontl@tlaconsultancy.co.uk

**Comment by syntaxerror** [comment]
So you don't have the problem any longer?
If that's the case, please close this issue, else add some more info.
Thanks!
