### ISSUE TITLE
No error handling in checkout, on t.ex. mail and cURL issues

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#482]
Just noticed yesterday that the error handling in the checkout sucks... ;)

T.ex. if there is mail issues the order will be placed when the customer clicks the confirm button, but there is nothing informing the customer about it, the button just loads before it becomes available to click again. The customer can therefore place the order several times, and even believe the order wasn't placed, and thus go order from someone else whit a working cart instead ...

To test, change to SMTP sending of mail and fill in non working mail credentials, activate Bank Transfer or COD, and go to checkout. Click confirm button ...

**Comment by syntaxerror** [comment]
Also applies to cURL issues it seems ... It can be reproduced with the 1.0.0 version of the Klarna module.

_Because it hast the CURLOPT_SSL_VERIFYHOST issue, fixed in GitHub, but not updated to Marketplace ..._

**Comment by cuneytsenturk** [comment]
https://github.com/arastta/addons/pull/14

Thanks Rune.

**Comment by syntaxerror** [comment]
Sorry to say Cüneyt, but the real problem in this isn't solved - only the bad code in Klarna module used to test.

The mail issue still exist, so does also any cURL or other issues on server to server connections.

Thus this issue should be reopened.

**Comment by cuneytsenturk** [comment]
I am closing this issue and Rune can create issue on [`arastta/addon`](https://github.com/arastta/addons)

**Comment by syntaxerror** [comment]
I don't like this kind of closing, without any kind of discussion.

It seems clear that the issue hasn't been understood, as it's not a addon issue, but a generic core issue.

You will not, and can not, fix all kind of possible errors caused by addons. Thus a failure to create orders properly, or tell they have been created, should be handled by the core itself.
