### ISSUE TITLE
Use SSL should redirect indexes

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#484]
When "Use SSL" is set to "Catalog" or "All Site (Catalog + Admin)", index sites should be redirected to https://

Now if you go to http://mysite.tld/ or http://mysite.tld/admin/ it stays on the http:// until you navigate to a sub site through menu or other links, or logs in.

In Joomla and other systems, all means all. ;)

**Comment by denisdulici** [comment]
Thanks Rune for reporting it 😉
