### ISSUE TITLE
Modules not up to date, missing name and save & close button etc.

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#485]
Noticed the following modules haven't been updated with support for at least "Name Field" and "Save & Close" button:

Account (Module Name field)
Affiliate (Module Name field)
Category (Module Name field)
Categories (Save & Close + Module Name field)
Filter (Module Name field)
Google Hangouts (Module Name field)
Information (Module Name field)
Login (Save & Close + Module Name field)
Manufacturer (Save & Close + Module Name field)
Store (Module Name field)

**The regular  Category module also should have support for selecting "Parent Category", same way as in Categories (Wall), as it's important for multistore support ..**.

**Comment by syntaxerror** [comment]
Further all modules should have an option to hide the display of "Module Name" in frontend ... ;)

**Comment by burakcakirel** [comment]
Actually, module names are not missing. It's about the Module structure. As you see, there are two types of Module. One is that working as instance, the other one is that working as static. So, module name is used only for the instance modules. It can be changed from language override for static modules.

Regarding "Parent Category" and "Show/Hide module name" feature;
I think it's better that submit a new idea to arastta.org.

Regarding "Save & Close" button;
Thanks, we're working on it. The commit will be sent soon :)

**Comment by syntaxerror** [comment]
OK, I see what you mean. But t.ex. for a multistore it sometimes makes sense to have different names on some modules, and that would not work with a language override. Anyhow I'm not going to fight this hard, and will be fine with your decision, and anyway I'm able to fix it with a vqmod (already done for one shop).

Parent category selection is something I would expect the module to have though, but still it's so minor that a extra idea for it only adds to the mess. Takes some time, but also this I can work around.

**Comment by burakcakirel** [comment]
Thanks Rune. You're free to create pull requests for them.

**Comment by syntaxerror** [comment]
Cant do PR as it's store specific workaround/hacks, doesn't fit globally, isn't flexible enough. T.ex it just raw code hacks to check domain and change value according to it ...
