### ISSUE TITLE
Mails doesn't respect address setting

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#487]
The mail templates doesn't respect the countries setting for address format.

T.ex. if country setting is:

> {company}
> {firstname} {lastname}
> {address_1}
> {address_2}
> {postcode} {city}

But mail still will use:

> {firstname} {lastname}
> {company}
> {address_1}
> {address_2}
> {city} {postcode}
> {zone} {country}

**Comment by cuneytsenturk** [comment]
Thank you Rune, I've fixed this issue. But it would be better if you test it.
