### ISSUE TITLE
URL's in mail templates get truncated

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#489]
Sometimes there is need for a full URL to a document download or something in the mail templates, t.ex. for the darn regret document required in some countries.

Best would of course be to support attachments, but anyhow ...

The text editor (TinyMCE) strips out the protocol and domain from the URL, replacing it with "../" when saving. Causing a non working link in the mail.

**Comment by cuneytsenturk** [comment]
Thanks Rune,
