### ISSUE TITLE
Ajax search not showing discount price

### ISSUE THREAD

**Issue by denisdulici** [arastta/arastta#491]
![2016-06-07_1010](https://cloud.githubusercontent.com/assets/5254835/15848947/720625f6-2c98-11e6-89eb-de82235301c5.png)

**Comment by cuneytsenturk** [comment]
![search-view](https://cloud.githubusercontent.com/assets/10936547/15852164/d9f65360-2ca8-11e6-86bb-15646bd60dc5.png)
