### ISSUE TITLE
missing locale variable at new language install

### ISSUE THREAD

**Issue by osworx** [arastta/arastta#50]
Since the variable locale is deleted, adding a new language results in this error:
`Notice: Undefined index: locale in ..\admin\model\localisation\language.php on line 10`

Either delete this field also in the db (and model) or re-add it.

**Comment by osworx** [comment]
Okay, same goes when an existing language is updated!

**Comment by denisdulici** [comment]
Just tried with language installation manually and from marketplace but couldn't reproduce such an issue. Same with language update. What is the Arastta version you're using?

**Comment by osworx** [comment]
1.0.4

**Comment by osworx** [comment]
AS long as this is in the model `$this->db->query("INSERT INTO " . DB_PREFIX . "language SET name = '" . $this->db->escape($data['name']) . "', code = '" . $this->db->escape($data['code']) . "', locale = '" . $this->db->escape($data['locale']) . "', directory = '" . $this->db->escape($data['directory']) . "', image = '" . $this->db->escape($data['image']) . "', sort_order = '" . $this->db->escape($data['sort_order']) . "', status = '" . (int)$data['status'] . "'");`
and no variable inside the view https://github.com/arastta/arastta/blob/master/admin/view/template/localisation/language_form.tpl
as long this error will happen.

`$data['locale']` refers to a request->post variable which is not set.

**Comment by denisdulici** [comment]
Now I can see this when adding/editing language but not installing language from marketplace/upload.

**Comment by osworx** [comment]
Yes, sorry forgot to mention that I did not install from the marketplace, instead did it by direct copying (FTP)
