### ISSUE TITLE
Languages version not updated at Marketplace

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#514]
The languages downloaded by the Arastta installer is the latest version (?), but at the Marketplace they ain't updated as they should (??), and are constantly falling behind..

![marketplace_not_updated](https://cloud.githubusercontent.com/assets/858132/17174492/981ab54c-540a-11e6-81b3-46bd9714e140.png)

Installed version 1.3.4.1
Latest version 1.3.1.2

**Edit! Actually it's the update server, and the displayed version at Marketplace, being wrong. The language pack itself is updated.**

**Comment by syntaxerror** [comment]
Same issue for English etc.
![language_updates](https://cloud.githubusercontent.com/assets/858132/17362714/10a06560-597f-11e6-850c-c9ae56a651ea.png)

**Comment by denisdulici** [comment]
This is not related with Arastta but Crowdin as its hook doesn't work properly. You know how to trigger that manually 😉

**Comment by syntaxerror** [comment]
Depends on how you see it, problematic for bot us and the users if languages are outdated. And since it was a ongoing issue over time with no reply in forum/PM it was added here - in the only issue tracker we have. ;)

If it's a Crowdin issue, I hope they have been notified with a detailed description, so they can fix it. They are quite fast fixing issues, as long as they know about it.

**Comment by denisdulici** [comment]
I see but there is no problem with getting the version within the Arastta core so there is nothing to be done here, through GitHub.
