### ISSUE TITLE
Update Center - Requirements and error handling

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#519]
The Update Center need some improving I think, regarding checking and displaying requirements (Your server doesn't meet the required settings for: ...), and also some kind of error handling when updates fails.

Now the script just runs for some time after pushing the update button, then it displays "Update process has been completed successfully.", even if nothing was updated.

![update_center](https://cloud.githubusercontent.com/assets/858132/17401134/8b8d2774-5a54-11e6-837d-047d0c7214ce.png)

**Comment by syntaxerror** [comment]
Note! Regarding the "Update process has been completed successfully." message, it could be some check at the end of the update, to check if version actually changed / is resent, before displaying.

**Comment by denisdulici** [comment]
There are already some checks for requirements such as xml and zip there. I'm curious about the second part as the system returns false for every step if it fails, starting from the download ending with the file mirror:
https://github.com/arastta/arastta/blob/master/admin/model/common/update.php#L72

**Comment by syntaxerror** [comment]
But no checks for other important server requirements etc., right?

Don't know if you remember when there was something wrong with the pack being downloaded, think it maybe was 1.3.4 files in 1.3.5 package or whatever it was (one problem with old unhandled issues is human memory). Then you got this issue, but there has been other reports in forum before this also.

So if there is a version check after files being updated, it doesn't work.

**Comment by denisdulici** [comment]
I've added another requirement check and a final check for the new version. Hope that helps 😉

**Comment by syntaxerror** [comment]
Sounds great, thanks. :)
