### ISSUE TITLE
1.4RC1 - Filter and sorting (drag and drop)

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#533]
Basic view (Drag and drop not supported in Advanced btw).
Go to 'Products', select 'Category' filter, and then 'Pants > Men'.
Then click on 'Sorting' (required to activate drag and drop).
**The category selection is reset/dropped ...**

**Comment by EnesErtugrul** [comment]
Drag & Drop sorting is designed only for Basic mode, not for Advanved because of B/C.
Sorting feature is not supported for sub-categories, yet. But planned to add it in the next releases.

**Comment by syntaxerror** [comment]
The Basic is to basic, so we don't use it much. Sorting by numbers in Advanced would be nice.
Anyhow, without filter possibility it's really not very usefully when there is more than a few products.

But speaking filters, those should remember the selection anyway. T.ex. after editing and saving a product. So the main issue isn't really the sorting function, but filter function, I guess.
_Edit! And the filters works equally "bad" in both Basic and Advanced._

**Comment by EnesErtugrul** [comment]
Event if it's not the case for you, most of the users (as far as I can see) use the Basic mode for daily operations. I agree with you it would be nice if sorting feature is implemented for Advanced mode, too. But you know we have a BC probem and listing pages are important part of our admin panel, so breaking it in the Advanced mode is not (unfortunately) a good idea.

+1 for remembering the filters after editing or saving. I will talk with @cuneytsenturk about it and hope to implement it during the RC releases.

**Comment by syntaxerror** [comment]
The Basic mode is great, for basic needs indeed. But especially the product edit should be extended, as it doesn't even show measure fields (length, width, height). Also I'm not sure sorting in Advanced would have to break anything important. But it's both another topic, so we can leave it for now.

Remembering the filters would make a lot of people happy, so let's focus on that then. :)

**Comment by EnesErtugrul** [comment]
> Remembering the filters would make a lot of people happy, so let's focus on that then. :)
> 👍

**Comment by syntaxerror** [comment]
Note that this reset/dropped selection also applies for pagination, selected site number.

T.ex.. if you try to disable languages you have no choice to select displaying all (unless editing settings), so you need to navigate to the next sites using the pagination in bottom. So going to site 2, select all, then disable - you're redirected back to the first site. Quite annoying when you need to handle a lot of countries, products etc. :)
