### ISSUE TITLE
1.4RC1 - ContextErrorException in customer_group_list.tpl

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#535]
Advanced error reporting activated, using Basic mode:

ContextErrorException in customer_group_list.tpl line 33:
Notice: Undefined variable: column_sortable

**Comment by cuneytsenturk** [comment]
I've tested it but not see this issue. 
Already added this  variable "column_sortable" look here =>https://github.com/arastta/arastta/blob/1.4-dev/admin/controller/sale/customer_group.php#L218

**Comment by syntaxerror** [comment]
Sorry, seems like it was a failed update test.
