### ISSUE TITLE
editor text (TinyMCE)

### ISSUE THREAD

**Issue by osworx** [arastta/arastta#55]
Whenever TinyMCE as editor is used, within the initialization this is written:
`target_list: [
               {title: 'None', value: ''},
               {title: 'Same page', value: '_self'},
               {title: 'New page', value: '_blank'},
               {title: 'LIghtbox', value: '_lightbox'}
              ]`
These strings should also be translated.

**Comment by denisdulici** [comment]
I thought TinyMCE supports multi-language, isn't translated?

**Comment by osworx** [comment]
Yes it does.
But if no language files are included, no translation is made.
And these vars are hardcoded and nowhere translated - these vars should be included in the language file.
e.g.
`$_['text_title_same'] = 'Same Page';`
`$_['text_title_self'] = 'New Page';`
and so on ..

and inside the template
`{title: '<?php echo $text_title_same; ?>', value: '_self'}`

**Comment by osworx** [comment]
I you agree, I can make a PR (hopefully with correct intends ..)
