### ISSUE TITLE
If incorrect hostname specified during install, app will get PHP timeout, 30s in my case

### ISSUE THREAD

**Issue by arnisjuraga** [arastta/arastta#568]
To reproduce: 
- enter incorrect "hostname" for MySQL server:

![image](https://cloud.githubusercontent.com/assets/2185289/18833664/7eb14132-83fa-11e6-8bb3-5fea1a7da3dc.png)

**Comment by denisdulici** [comment]
I get the following result:

![2016-09-27_1209](https://cloud.githubusercontent.com/assets/5254835/18867059/564def5e-84ab-11e6-9593-120488116678.png)

**Comment by arnisjuraga** [comment]
How fast does it appears for You?

I have tried in 2 different servers. The same problem - connection try takes too much time, and if my server has 30s script execution time, it will end up with error. Anyway - few seconds max must be enough, to test server connection?

**Comment by syntaxerror** [comment]
I did test with:
max_execution_time = 15;
mysql.connect_timeout = 15;

I even tested with 2 on both. Got same result as Denis, in something around 1-2 sec.

Badly overloaded hosting?

**Comment by syntaxerror** [comment]
**Found something!**

If I use the MySQLi driver, all is fine. But if I switch to MySQL (PDO) driver, I get the same result as @arnisjuraga on a cPanel server with native PHP 5.5

But, if I switch to self configured PHP 5.5 or newer. and ensures mysql, mysqli, pdo_mysql etc is activated all is fine.

Maybe your servers just don't have MySQLi activated @arnisjuraga ?

Anyhow, it seems like the installer needs some checking on this, to avoid throwing this confusing internal server error in peoples face. :)

**Comment by arnisjuraga** [comment]
I have MySQLi activated. MySQL is runnnig on local machines.
If I input correct hostname (e.g. "127.0.0.1" or "localhost"), the I received immediate response on success or error message, everything is fine.

The problem is only with "incorrect" hostname, which does not responds on MySQL connections.

**Comment by syntaxerror** [comment]
> MySQL is runnnig on local machines.

What does that actually mean? Is it running on localhost, same server/machine as the website, or other?
If there is no MySQL instance running on the same machine as your website (Arastta install), you get the same problem/result as in my test, it doesn't find the needed stuff.

**Comment by arnisjuraga** [comment]
same server/machine. One instance. With php script exeuction time set to 30 seconds.

**Comment by arnisjuraga** [comment]
Yes, the problem seems to be because of lack of timeout on MySQL connection. If the hostname is not accessible, then timeout will hit PHP execution time.
