### ISSUE TITLE
PDF Invoices failing

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#581]
I finally found a store having this problem mentioned by t.ex. Hermann in the forum, and then being able to figure out some parts by investigating the tables (order and customer related).

This store is migrated from OC 1.5 originally. First updated to 2.0, then to Arastta using the Opencart 2 Migration Tool (from Marketplace), but I don't know if that is relevant yet.

From the investigation I found all orders failing having a registered customer, both new and old ones, but not why.

Though ... if I replace customer id on the order, in the order table, with 0 - **the pdf generation works** also for those orders.

I don't find any obvious problems withe customer or address table, so I suspect it's only the lookup failing.

**Comment by syntaxerror** [comment]
Recreated the issue on a non-migrated test site, so it's not related to migration.
All orders with registered customers if failing generating invoices.

Arastta 1.4.2
PHP 5.6.27
DB 5.6.33
Server API CGI/FastCGI

Note! After adding the changes from the '[Multiple print invoice on admin order page](https://github.com/arastta/arastta/commit/08a587daa7f58c0e26289fef2c7b1cb0644243a6)' commit, we don't get the white empty page any longer, instead this is displayed (notice file name is missing):
![arastta_invoice_fail](https://cloud.githubusercontent.com/assets/858132/19836492/ae304460-9eaa-11e6-9875-06e58c4dc0df.png)

**Comment by syntaxerror** [comment]
Seems like the customer can print the invoice from his/her account, in frontend, after login.
Ref: https://arastta.org/forum/still-problem-with-sending-invoice-by-mail#reply-2294

If I'm not mistaken, the PDF print in admin is also using frontend files, so maybe it's just a issue with access restrictions.

**Comment by rcsofttech85** [comment]
i do have the same problem.
![inoice](https://cloud.githubusercontent.com/assets/17738213/21593381/6b4bf6f2-d13c-11e6-9d67-40fd8765ccd1.png)
