### ISSUE TITLE
vq2-system_modification_system_library_language.php error

### ISSUE THREAD

**Issue by pekka2** [arastta/arastta#59]
line 74:
require(VQMod::modCheck(modification(modification($file), modification($file)));
to:
 require(VQMod::modCheck(modification(modification($file), modification($file))));
line 80:
require(VQMod::modCheck(modification(modification($file), modification($file)));
to:
require(VQMod::modCheck(modification(modification($file), modification($file))));
same lines 86 and 100
What is original file to this error?

**Comment by denisdulici** [comment]
Where do you exactly get such an error?

**Comment by pekka2** [comment]
Hi

This issue go this way:
1. Copy new language file.
2. Install new OCMOD xml-file
2. Language file is wrong directory or OCMOD file is not found search string in path file.

**Comment by denisdulici** [comment]
Can you please share the files (language, ocmod etc) so we could try to reproduce it?

**Comment by pekka2** [comment]
What is your email ? Can you send it my PM?
Ps. Error is in file system/modification/system/library/language.php
There is double modification, when edit this:
require(modification(modification($file)));
to:
 require(modification($file));
this is work.

**Comment by cuneytsenturk** [comment]
fixed here https://github.com/arastta/arastta/pull/105

**Comment by denisdulici** [comment]
Pekka, were you able to test this with Arastta 1.0.8 ?
