### ISSUE TITLE
Missing SEO URLs

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#591]
Brands and Returns doesn't use SEO URL's
Ref.: https://arastta.org/forum/missing-2-seo-url

Demo:
http://demo.arastta.org/index.php?route=product/manufacturer
http://demo.arastta.org/index.php?route=account/return/add

**Comment by cuneytsenturk** [comment]
@denisdulici  added Arastta 1.5 => [#604](https://github.com/arastta/arastta/pull/604)
