### ISSUE TITLE
Error click image in "Manage Image" form

### ISSUE THREAD

**Issue by wahono77** [arastta/arastta#605]
If I select (click) image in root folder, that is OK.
But if I go to sub folder and click image, I got error as in picture.

Thanks
![error-arastta](https://cloud.githubusercontent.com/assets/3787240/20628867/3298f520-b35b-11e6-98e1-c21960bc6484.png)

**Comment by cuneytsenturk** [comment]
@wahono77 Please tell me which Arastta version you use.

**Comment by wahono77** [comment]
I use Arastta 1.4.2 Stable [ Kolari ] 21-October-2016 10:30 GMT +2
And this problem only if I use "Advance" editor, if I switch to "Basic" editor this problem is gone

**Comment by cuneytsenturk** [comment]
I cannot reproduce this issue. Please send me a PM on our forum with your site's credentials, so I can check it
