### ISSUE TITLE
missing language variable

### ISSUE THREAD

**Issue by osworx** [arastta/arastta#61]
In admin/language/en-GB/sale/customer.php a variable is missing
`$_[entry_send_email'] =`
But - what for is it?
Additional a help (tooltip) for this field would be good to have

**Comment by brettwhiteman** [comment]
Also missing in the marketing/affiliate.php language file

**Comment by denisdulici** [comment]
That is used to send the details via email after adding a new customer from admin panel.

**Comment by osworx** [comment]
Okay, and who is adding the fields (text and help) now?
