### ISSUE TITLE
1.5 RC1 - Backup Restore - Error with Basic error reporting

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#615]
Error reporting Basic
PHP Version	5.6.28
Database Version	5.6.34-log
Server Interface (SAPI)	cgi-fcgi

Took a backup of default demo data, then tried to restore it:
![backup_restore](https://cloud.githubusercontent.com/assets/858132/20719597/200e8688-b665-11e6-9838-479d27ceb8a5.png)

**Comment by syntaxerror** [comment]
See #617

**Comment by denisdulici** [comment]
I was not able to get such an error Rune, even with Display Errors set as Advanced 😢

**Comment by syntaxerror** [comment]
Using https and 'Security -> Use SSL' set to no ?
https://github.com/arastta/arastta/issues/617#issuecomment-266566542
