### ISSUE TITLE
HTTPS - Notice: Undefined index: HTTP_REFERER

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#617]
Related: #615 and #616

When a new store is installed / loaded over https it will have a lot of issues related to undefined HTTP_REFERER until the 'Security -> Use SSL' setting is found and changed (or remembered changed).

Thus I think there is two things needed:

1. Define if SSL is to be used in installer, selection or auto detection, and set the security config according to it when installing the system.
2. Display a warning if the site is browsed over https when 'Security -> Use SSL' is set to no.

Alternatively define HTTP_REFERER correctly anyway, make it a setting / add also store id 0 to stores table or something. It would maybe also solve other issues, like #561

**Comment by denisdulici** [comment]
Checking if HTTP_REFERER is defined in Customizer seems to be enough as it's not used in any other place directly.

**Comment by syntaxerror** [comment]
OK, so that solves one part of the SSL issue. But not the other parts of the system, like backup (#615) and checkout.

T.ex if standing in the cart and change quantity on a product:
> Notice: Undefined index: HTTP_REFERER in /catalog/controller/checkout/cart.php on line 403
> Notice: Undefined index: HTTP_REFERER in /catalog/controller/checkout/cart.php on line 404
> {"location":"module"}

Reopen and reconsider please.

**Comment by qroft** [comment]
I am still having this error at my checkout cart. Is there some kind of workaround, maybe even via an ugly .htaccess redirect that checks the URL ?
