### ISSUE TITLE
1.5 RC1 - All reports -> UndefinedMethodException in graph.php line 26

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#618]
![reports](https://cloud.githubusercontent.com/assets/858132/20724800/583ef21e-b678-11e6-963b-1684bf871be6.png)

**Comment by cuneytsenturk** [comment]
https://github.com/arastta/arastta/commit/5ca5001b3d8356e77a9c600319c85529bb2f488c fixed this issue
