### ISSUE TITLE
1.5 - Captcha broken

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#630]
After updating to 1.5 Captcha seems broken.

In backend Captcha's is displayed as disabled in the list, even if set to enabled.

In frontend:
![captcha_frontend](https://cloud.githubusercontent.com/assets/858132/21265203/fc25e7ce-c3a8-11e6-883c-56e67eeea7f3.png)

**Comment by syntaxerror** [comment]
Some more info, after looking closer at it.

Basic Captcha seems to work.

reCaptcha tries to load the 'Basic Captcha' template, and thus outputs (Advanced Error Reporting):

> ContextErrorException in basic.tpl line 5:
> Notice: Undefined variable: captcha

_So new stores using no Captcha or Basic Captcha works fine, but updated stores using reCaptcha is probably "broken" if the store owners isn't aware of this problem._

**Comment by fathira** [comment]
i feel same problem
