### ISSUE TITLE
Google Analytics warning

### ISSUE THREAD

**Issue by fathira** [arastta/arastta#631]
I copied google analytic script in google then paste Analytics property settings:
However saving this code failed with the following warning:
Warning: JavaScript code is required! i
see my code 
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-12345678-1', 'auto');
  ga('send', 'pageview');

</script>

nb:  12345678-1 not original

**Comment by syntaxerror** [comment]
Confirmed!

Google Analytics is also broken after upgrade from 1.4.2 to 1.5.0, the code is changed and not active. And it's also not possible to insert the correct code, then you get the error mentioned by @fathira here.

**Comment by syntaxerror** [comment]
I tested the code change here, but it seems like it's still broken.

Also it still displays as disabled in admin list, when it actually is enabled.

**Comment by cuneytsenturk** [comment]
Did you test edit google analytics? If you edit it and enter javascript key, it works.
@syntaxerror Please edit this extension configuration after check it.

**Comment by syntaxerror** [comment]
Yes, sure I did.

It still displays as disabled in admin, and outputs nothing in front.

**Comment by syntaxerror** [comment]
But yes, the JavaScript is saved, after being striped. But still doesn't work. :)

**Comment by cuneytsenturk** [comment]
Are you sure don't work it? Hopefully, You can do enable this extension. because I've checked and it works.

=> http://screencast.com/t/eCeSC4CfX

**Comment by syntaxerror** [comment]
To be more precisely, there is just displaying an Array in custom templates. So B/C isn't kept it seems.
![custom_template](https://cloud.githubusercontent.com/assets/858132/21481343/3ded6588-cb6f-11e6-91fe-63f2bdcbc080.png)

Anyhow, the admin list display is broken:
![analytics_edit](https://cloud.githubusercontent.com/assets/858132/21481392/cb3c7d66-cb6f-11e6-962c-1fa0fa0d43e7.png)
![analytics_disabled](https://cloud.githubusercontent.com/assets/858132/21481395/cfbba268-cb6f-11e6-9244-3f079654f480.png)

Test it on a updated site please.

Oh, cache is cleared of course. :)

**Comment by syntaxerror** [comment]
Damn ... we have to rewrite the header file, applying the other changes to make it work.
https://github.com/arastta/arastta/commit/83bb387ab3cb80dfa9934b7869c9497b325b4b8d#diff-8643627ae225d8f9e38402706af6529a + https://github.com/arastta/arastta/commit/861f35d96c0d832988df30f37a1b85db517fe2b0#diff-8643627ae225d8f9e38402706af6529a

Edit! To get the full picture of needed template changes, look at https://github.com/arastta/addons/commit/fbd7e8ff2d3713e8ee072e2ed8714d05ea7253e6

Guess we will see some angry users having trouble because of broken B/C in templates, regarding both Captcha and Analytics ...
