### ISSUE TITLE
changing /admin url

### ISSUE THREAD

**Issue by rcsofttech85** [arastta/arastta#634]
getting blank page after changing admin folder name

**Comment by syntaxerror** [comment]
You should use the support forum, and provide some usefull information.
https://arastta.org/forum

By the way! You should NOT change any folder name ... sure you break things then.

**Comment by rcsofttech85** [comment]
@syntaxerror  i created a post on support forum, waiting for the support :)
https://arastta.org/forum/change-access-path-to-admin

**Comment by cuneytsenturk** [comment]
@rcsofttech85 Thanks. We will answerd on the [Arastta Forum](https://arastta.org/forum/change-access-path-to-admin)
