### ISSUE TITLE
Search not working for non-latin chars

### ISSUE THREAD

**Issue by djokerat** [arastta/arastta#635]
after update to1.5...
Click on a tag to a product
www.webpage.com/product/search?tag=tag name
or
www.webpage.com/product/search?tag=tag
redirect 404

how to fix it?

**Comment by syntaxerror** [comment]
Provide a real URL, real tags, and some system info please.

System information: https://arastta.org/docs/user-manual/tools/system-information
Arastta settings (especially SEO): https://arastta.org/docs/user-manual/system/settings/seo

**Comment by djokerat** [comment]
Use SEO URLs:  Yes
Remove index.php: Yes
Add Suffix to URLs: No
Add Category to Products URLs: Only Last Category
Translate URLs: No
Add language code to URLs: No
Use canonical links: Yes
www Redirection: Yes
non-SEO to SEO URLs Redirection: Yes

**System:**
Platform: Arastta 1.5.0 Stable [ Nairobi ] 14-December-2016 12:00 GMT +3
PHP Version: 5.3.29
PHP Built on: Linux mars.superhosting.bg 3.10.0-427.10.1.lve1.4.7.el7.x86_64 #1 SMP Sat Apr 2 12:09:46 EDT 2016 x86_64
Database Version: 5.5.52-cll
Database Collation: cp1251_general_ci
Web Server: Apache
Server Interface (SAPI): cgi-fcgi

**The problem is only noticeable with tags written in Bulgarian language. When tags of English (latin) tag respond correctly.**

**Comment by syntaxerror** [comment]
> **The problem is only noticeable with tags written in Bulgarian language**. When tags of English (latin) tag respond correctly.

This is important information, and I guess it's a issue with the Bulgarian charset then. Could you provide some real examples of tags/words/letters failing, for devs to test?

PS! Your PHP version is very old, you should consider updating it to something faster and more secure.

**Comment by djokerat** [comment]
Tags: allwaves, маска, слаба коса с кератин и шоколад, подсилваща и заздравяваща маска, за изтощени дължини и краища, незабавно разплитане и подхранване, подходящ за тънка, слаба или изрусявана коса, подобрява разресването, подходяща за използване всеки ден

**Comment by djokerat** [comment]
how to fix it?

**Comment by djokerat** [comment]
please, how to fix Bulgarian charset seo tag?!

**Comment by djokerat** [comment]
after 3+ months still nobody???

**Comment by denisdulici** [comment]
That is not directly related with Arastta but how your server's PHP encodes the query string: http://stackoverflow.com/a/3368484

![2017-04-12_1728](https://cloud.githubusercontent.com/assets/5254835/24963650/d80e67a2-1fa7-11e7-8ecd-60646bc16166.png)

**Comment by syntaxerror** [comment]
Sometimes the servers need help. :)
Is rawurldecode used on the query string?

**Comment by denisdulici** [comment]
Change this line: https://github.com/arastta/arastta/blob/master/system/library/route.php#L40

`$query_string = rawurldecode($this->uri->getQuery());`

Must discuss this before adding to the core.

**Comment by djokerat** [comment]
**THANK YOUUUUUUUUU!**
