### ISSUE TITLE
footer seo url missing

### ISSUE THREAD

**Issue by fathira** [arastta/arastta#637]
footer seo url missing.
 About Us,Delivery Information,Privacy Policy,Terms & Conditions  work fine
all other items now non seo url ( php root ) induced cart check out 
( footer and check out  url both as oc )
product seo url fine 
arastta 1.5 manually code updated (parched)  from githhub after missing this

**Comment by syntaxerror** [comment]
What are those "all other items"?
Your own added information pages, or what?
Have you checked the new "URL (Redirect) Manager": https://arastta.org/blog/arastta-1-5
And surely you cleared your cache ...

I think you should rather post in the support forum, until it's sure it's a real issue, and not just your installation being broken/miss-configured again ...

**Comment by syntaxerror** [comment]
Also ...

Provide a real URL, and some system info please.

System information: https://arastta.org/docs/user-manual/tools/system-information
Arastta settings (especially SEO): https://arastta.org/docs/user-manual/system/settings/seo

**Comment by fathira** [comment]
may be that a miss behavior of server idont know. now uninstall and install new one 1.5 .then then code updated manually  it is work fine no problems sorry
