### ISSUE TITLE
Redirect issues with "Keyword for Admin Panel"

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#638]
There are some redirecting issues when using "Keyword for Admin Panel"

Most importantly the "Forgotten Password" feature doesn't work. You can type your mail, but you're just being redirected to store front, and the mail with the new password requested is NOT sent - so a admins who have lost their password is locked out from admin.

Also when you log out, or are being logged out by expired session, you're redirected to the store front. This isn't actually a big deal, but annoying for some.

**Comment by rcsofttech85** [comment]
@syntaxerror  Just now i changed my password working perfectly.

**Comment by cuneytsenturk** [comment]
@syntaxerror Yeap,I am agree @rcsofttech85 . I've tested forgetten password. it works.

**Comment by syntaxerror** [comment]
I hardly believe @rcsofttech85 was able to test it, since he has done very strange things with his setup, and shouldn't be posting on GitHub at all: https://github.com/arastta/arastta/issues/634

And maybe you did forget to test the keyword setup @cuneytsenturk, because it doesn't work on several stores according to the description above. You can test it at https://sedev.no/arastta/admin/?test using info [at] arastta.com

![settings](https://cloud.githubusercontent.com/assets/858132/21603353/545f3d32-d1a5-11e6-8043-facfbcae1cef.png)

![seo_settings](https://cloud.githubusercontent.com/assets/858132/21603390/954143fe-d1a5-11e6-9ba0-7ef6624d89fd.png)

**Comment by rcsofttech85** [comment]
@syntaxerror #634  is not a setup issue, its a security concern,anyway feeling guilty about writing here. sorry

**Comment by syntaxerror** [comment]
That's your misunderstanding.

**Comment by denisdulici** [comment]
Thanks Rune for reporting it 😉
