### ISSUE TITLE
Problem with deleting sub-menus

### ISSUE THREAD

**Issue by denisdulici** [arastta/arastta#642]
https://arastta.org/forum/bug-menu-issue

In short, when you delete a sub-menu, it also removes all other sub-menus from the screen but in fact they are in database. Refreshing the page brings the other sub-menus back.

**Comment by syntaxerror** [comment]
Sounds like it's kind of related to the old known issue in #392, nice if both could get the needed love at the same time, and maybe the number of supported levels also could be extended then. 

Sorry if you feel I'm going of topic, but I think the menu system could need some overall rewrite, and it would be good to do it all at once. ;)
