### ISSUE TITLE
problem with pre-order

### ISSUE THREAD

**Issue by djokerat** [arastta/arastta#652]
Available in 50 pieces, to cart the product is marked as pre-order

**Comment by syntaxerror** [comment]
You should post support cases in the forum, and also add some useful and detailed information. Like description and/or images of your product settings, system info like version etc. etc.

It's most likely not a bug/issue, but a miss-configuration in your setup.

The forum is here: https://arastta.org/forum

**Comment by djokerat** [comment]
![bug-pre-order](https://cloud.githubusercontent.com/assets/24839389/22151491/de79c968-df26-11e6-9387-322ec22ab503.jpg)
![bug-pre-order-2](https://cloud.githubusercontent.com/assets/24839389/22151495/e19fae8c-df26-11e6-8531-c3780fa5ad88.jpg)
ver. 1.5.1

**Comment by syntaxerror** [comment]
English please

**Comment by djokerat** [comment]
Ver. 1.5.1

stock: 50
min: 1
removal from stock: Yes
Status: availability (with Pre-Order)

**Comment by syntaxerror** [comment]
Confirmed and fixed. You can patch and test: https://github.com/arastta/arastta/pull/653/files

Thanks for reporting it.

But in future, please install a fresh English demo to confirm it's a real issue, and to collect some more useful data to include, before posting it as a issue. Or better, use the support forum first: https://arastta.org/forum
Posting a one liner like this makes us waste a lot of time.

**Comment by djokerat** [comment]
it is ok

Thanks!!!
