### ISSUE TITLE
problem with pre-order / with option

### ISSUE THREAD

**Issue by djokerat** [arastta/arastta#657]
Available 4 option with x 20 count
![untitled-1](https://cloud.githubusercontent.com/assets/24839389/22406566/e4129830-e65d-11e6-8a23-61054cef6929.jpg)

![untitled-2](https://cloud.githubusercontent.com/assets/24839389/22406567/e414ec20-e65d-11e6-86d0-68cf4356a659.jpg)

In product - Clients parts ... oprtion pre-order is not included
![untitled-3](https://cloud.githubusercontent.com/assets/24839389/22406568/e41e571a-e65d-11e6-8030-a18c0c4e9eeb.jpg)

**Comment by syntaxerror** [comment]
There is no pre-order on options, it hasn't been planed or coded.
Options was planed to be improved on it's own for 1.5, but it was not completed.

So it's not a real issue/bug, but a feature request imho.

Some related:
Idea: https://arastta.org/ideas/idea/5-options-model-sku-support
Issue: https://github.com/arastta/arastta/issues/187

**Comment by syntaxerror** [comment]
PR fixing this is merged, please close this issue.
Ref #681
