### ISSUE TITLE
Language Overrides -> Adding click to open URL code fails

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#658]
When adding a URL with a click to open code in a language override, it fails because slash is added in front of the double quotes, while it should happen only for single quotes.

T.ex if adding a code like
`Free Shipping - <a href="http://mystore.tld/free-delivery">Click here to see if you're in our free delivery zone</a>`

It will be saved as
`Free Shipping - <a href=\"http://mystore.tld/free-delivery\">Click here to see if you\'re in our free delivery zone</a>`

Ref. https://arastta.org/forum/adding-url-to-language-override

**Comment by denisdulici** [comment]
Those are added to escape quotation:
https://github.com/arastta/arastta/blob/master/admin/model/system/language_override.php#L213

Not sure if there is another way.

**Comment by syntaxerror** [comment]
What about str_replace only for single quote, since that is what is used in language files. There shouldn't be any defines using double quotes?

**Comment by denisdulici** [comment]
You're right, we use single quote for core language files but I've seen a lot of OC extension devs using double quotes in their language files 😢

**Comment by syntaxerror** [comment]
Hm ... yes, then it's tricky indeed. Sad thing devs not using standards.

**Comment by syntaxerror** [comment]
Seems quite "impossible", so I think I'm just closing it for now.
