### ISSUE TITLE
New extensions in 1.5+ displaying as disabled in admin, when they are enabled.

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#659]
Refs:
https://arastta.org/forum/google-analytics-isssue
https://arastta.org/forum/google-re-captcha-issue#reply-2659
https://github.com/arastta/arastta/issues/631#issuecomment-269200828
https://github.com/arastta/arastta/issues/631#issuecomment-269202829

**Comment by cuneytsenturk** [comment]
Is this a clean installation or update?

**Comment by syntaxerror** [comment]
Personaly I have not seen it in any fresh installs of 1.5.3, only in updated stores.
But in the forum posts Breck told it was a new store, maybe ask there for details about this.
