### ISSUE TITLE
Customizer error: HTTP ERROR 500

### ISSUE THREAD

**Issue by FractalFragger** [arastta/arastta#662]
when trying to change anything on the customizer in your cart i get

The silverbroomstick.co.uk page isn’t working

silverbroomstick.co.uk is currently unable to handle this request.
HTTP ERROR 500

permissions are 755 on the folder where the customiser.css file is meant to be but it doesnt seem to be writing to a file

**Comment by syntaxerror** [comment]
I think you need to add some more info, like which design you're trying to modify, and some system information: https://arastta.org/docs/user-manual/tools/system-information

**Comment by FractalFragger** [comment]
Please be aware that I raised this over two months ago

It does not matter what design I am trying to modify. The customiser simply does not work

Please fix!

**Comment by syntaxerror** [comment]
Nobody can fix anything if you don't care to add any useful info, making it possible to recreate the issue elsewhere. And so what if you added it years ago! The Customizer does indeed work on all our tested installs.

**Comment by FractalFragger** [comment]
EDIT by Denis: Go somewhere else.

**Comment by syntaxerror** [comment]
Well, have a nice day/evening yourself. Wish you all the best. :)
