### ISSUE TITLE
Arastta 1.5+ SEO - URL's failing

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#664]
Related to https://github.com/arastta/arastta/issues/661 and https://github.com/arastta/arastta/pull/604 I assume.

In Arastta 1.5+ I have found some URL's failing, when **non-SEO to SEO URLs Redirection** is **Activated**.

For search it fails if you search for several words at once (like "My Search Term"), then you get a "The requested page was not found", or gets redirected to frontpage.

For "badly" written payment modules, using other callback/confirmation URL than **payment/** it will also fail, even after that fix in #661, and the same goes for custom checkouts using own URL's (like Klarna Checkout etc).

So there is quite some BC issues in this it seems.

**Comment by syntaxerror** [comment]
Note that also the category select in Facebook Store feed seems affected.
Only thing making it work is to turn of SEO, "**Use SEO URLs: No**".
![fb-store](https://cloud.githubusercontent.com/assets/858132/22792390/3b1db4a8-eef5-11e6-8db6-f670265cc162.png)

```
        // Do not generate SEO URLs for feeds
        if (substr($route, 0, 5) == 'feed/') {
            return true;
        }
```

**Comment by denisdulici** [comment]
**non-SEO to SEO URLs** Redirection was active since the beginning but as the SEO URLs were being generated only for the specified links, it was not affecting such parts. However, we had to enable SEO URLs for all links after #604 .

Going to test search + feeds and add exceptions but don't think we can do anything for bad/custom modules, right?

**Comment by syntaxerror** [comment]
The bad/custom modules is tricky indeed, there probably is a few OC payment modules not working any longer, but those mostly don't have any common standard for callback etc. neither. So we probably just have to deal with them case by case, rewriting the module, or add exception through mods I guess.

**Comment by denisdulici** [comment]
OK, going to add an exception for feeds and search 😉
