### ISSUE TITLE
Products Module - Displaying unpublished products

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#666]
The new products module is displaying unpublished products in all types except featured, until cache is cleared.

**Comment by syntaxerror** [comment]
Note that cache also needs to be cleared to display changes in title, description and price in the new products module.

**Comment by denisdulici** [comment]
How did you unpublish these products? From edit or list page?

**Comment by syntaxerror** [comment]
Changes in title, description etc. is clearly on edit. For unpublishing I don't remember which, or both, and I don't think it's matters as it seems like more of a cache issue.

**Comment by syntaxerror** [comment]
But since you asked, I have now tested both again. Unpublishing from both list and edit, gives same result, product still displaying till cache is manually cleared.

And the cache settings is default, from install:

![cache](https://cloud.githubusercontent.com/assets/858132/23397663/28c1d67a-fda2-11e6-869a-276a8f6f8561.png)

**Comment by denisdulici** [comment]
You're right, module cache must be cleared automatically after product edit/delete.
