### ISSUE TITLE
Recurring Profiles - Profile price doesn't apply

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#667]
When using **Recurring Profiles** the price for the selected profile doesn't apply to the product or cart, it will always use the default price set on the product.

Most normal would anyhow probably be to set the price to zero in products data, and then display the lowest profile price as start price on product display, and have live update when selecting another profile.

Anyhow, as fare as I can see, the **Recurring Profiles** doesn't work as they should regarding prices.

![productdisplay](https://cloud.githubusercontent.com/assets/858132/23124337/23e2c692-f775-11e6-8393-33a4f7408245.png)

![cart_display](https://cloud.githubusercontent.com/assets/858132/23124340/26acec2c-f775-11e6-9b15-192c7643f269.png)

Btw! Also, if it's only one profile on the product, it doesn't make much sense to display a dropdown. Would be better to display the correct price and info directly.

**Comment by denisdulici** [comment]
Lets continue this under #668
