### ISSUE TITLE
Using 'View all' to select t.ex. categories fails when product is saved

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#671]
Noticed that if you click on 'View all' and then select t.ex. several categories, only one category selection is saved on the product.

But if you just write the category names and select them from the "drop-down", they are saved nicely.

I think this also applies to other fields having this new 'View all' function, and it applies to both Basic and Advanced view.

**Comment by denisdulici** [comment]
I just tried the "View All" for categories and it worked fine for me :( Is this a clean installation? Version?

**Comment by syntaxerror** [comment]
It was "discovered" on a migrated Arastta 1.5.4, but the same issue is confirmed on a clean 1.5.x install (my demo, now 1.5.4) when trying to add one more category to the 'AEO Denim' product.

Tested in both Firefox, Vivaldi, Chrome and Edge.

**Comment by syntaxerror** [comment]
Btw! Denis, did you **save the product** - and then looked at the categories?

Maybe I was unclear, but:
> only one category selection **is saved** on the product

Meaning, you don't see the problem before after trying to save the change. :)

**Comment by denisdulici** [comment]
Now I got it 😉 @cuneytsenturk working on it. Nice found 😉
