### ISSUE TITLE
Add new stock status gettinh error

### ISSUE THREAD

**Issue by cuneytsenturk** [arastta/arastta#685]
![add_new_stock_status](https://cloud.githubusercontent.com/assets/10936547/24198435/fad67cd0-0f16-11e7-83db-24cb2030c7e5.png)

**Comment by syntaxerror** [comment]
~~I think it's related to #680 and #683~~

**Comment by cuneytsenturk** [comment]
This issue reason varibles not check isset @syntaxerror  You can look line 61 and 73.

I think it is not related to #680 and #683

**Comment by syntaxerror** [comment]
OK, just haven't seen it anywhere before, and thought it was the only change since previous versions.

Btw! Line 61 seems to be yours, and line 73 mine. :)

**Comment by syntaxerror** [comment]
Added PR #688 to fix this.
