### ISSUE TITLE
1.6-dev - Undefined index in mail

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#687]
Tested registering a new customer in a clean install of latest code from 1.6-dev branch as of 2017.03.23

The welcome mail looks like this:
![welcome](https://cloud.githubusercontent.com/assets/858132/24268846/e6af1a12-1017-11e7-8246-c6d76ab31140.png)

**Comment by denisdulici** [comment]
There must be something wrong here as the demo files are intended to be used only during new installation of Arastta and/or language, to insert the content to the database.  I mean the content of such emails must come from database.
