### ISSUE TITLE
1.6 RC2 - Blog and site path (breadcrumbs) issue

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#693]
The blog is displaying the "component" name in site path (breadcrumbs), and not the menu item name, as I would expect.

![blog_fp](https://cloud.githubusercontent.com/assets/858132/24831452/32ce57aa-1ca2-11e7-9513-6104748b2488.png)

Also when you select a blog item, it only displays the item name. Not the menu item name in front, nor the category or "component" name.

![blog_item](https://cloud.githubusercontent.com/assets/858132/24831459/5638236a-1ca2-11e7-9001-ca974ae0c4a6.png)

**Comment by cuneytsenturk** [comment]
Thanks Rune, I've fixed it.
