### ISSUE TITLE
1.6 RC2 - Blog and reviews

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#694]
There are several language strings using review/reviews, while it should be comment/comments on blog items:

https://github.com/arastta/arastta/blob/1.6-dev/catalog/language/en-GB/blog/post.php#L14
https://github.com/arastta/arastta/blob/1.6-dev/catalog/language/en-GB/blog/post.php#L15
https://github.com/arastta/arastta/blob/1.6-dev/catalog/language/en-GB/blog/post.php#L18
https://github.com/arastta/arastta/blob/1.6-dev/catalog/language/en-GB/blog/post.php#L42-L43

**Comment by cuneytsenturk** [comment]
Thanks Rune 😉
