### ISSUE TITLE
1.6 RC2 - Blog post - Product should be post

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#695]
Product should be post / blog item I assume:
https://github.com/arastta/arastta/blob/1.6-dev/admin/language/en-GB/blog/post.php#L75

And this should be?
https://github.com/arastta/arastta/blob/1.6-dev/admin/language/en-GB/blog/post.php#L83

**Comment by cuneytsenturk** [comment]
Thanks Rune @syntaxerror
