### ISSUE TITLE
1.5.1+/1.6 RC2 - Still redirect issues with "Keyword for Admin Panel"

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#697]
Just tested password reset for admin (ref #638), using the same settings, and it's still not completely fixed.

The sending of mail with link works fine, and you stay on the login. But the link in mail doesn't include the needed keyword, thus the link doesn't work.

If you manually add the keyword to the end of the link you can enter the password change page, but the password change still doesn't work, you're just redirected to the frontpage and the password remains unchanged.

**Comment by denisdulici** [comment]
Thanks Rune, available since day 1 😉

**Comment by syntaxerror** [comment]
Hi Denis, you fixed the link it seems. But what about the second part of the issue?

> If you manually add the keyword to the end of the link you can enter the password change page, **but the password change still doesn't work, you're just redirected to the frontpage and the password remains unchanged.**

**Comment by denisdulici** [comment]
That happened because you most probably clicked the link once without the keyword. It wont happen now.

**Comment by syntaxerror** [comment]
OK I'll test it later. Thanks.
