### ISSUE TITLE
Stay on admin login, when using "Keyword for Admin Panel"

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#698]
When you don't use "Keyword for Admin Panel" you stay on admin login page after logging out, or being logged out by expired session.

But when you're using "Keyword for Admin Panel" you're being redirected to store front, which is a bit annoying for the users, since they need to add the address again, and then log in.

Ref. #638

**Comment by denisdulici** [comment]
Emm.. Not sure about how it should be, especially from the security perspective as typically when you logout, you get out and close.

**Comment by syntaxerror** [comment]
When you don't use a keyword, you stay on login screen. People expect it to be as that.

Typically the admin session is expired, becaus the store admin gets bussy in phone or something else.

Still I understand your concern, someone leaving a browser with the keyword displayed. But hey, that would normaly only happen "in house". If you use a public available computer to manage your store and just leave it ... well ... :)

**Comment by denisdulici** [comment]
I would prefer the current usage but I'm fine with both, just need to make such a decision. It reminds me Security vs Liberty 😉

**Comment by syntaxerror** [comment]
For me and you it's probably not a issue, that the redirect happens.
But for some busy, and maybe also stressed up, store admins - it can make their head spin. Don't ask me why, but someone just hates computers and every unnecessary typing. :)

**Comment by denisdulici** [comment]
I just checked and this is how it works with Akeeba Admin Tools too. Such a feature doesn't come enabled by default and those that just hate computers and every unnecessary typing are not forced to enable it. Furthermore, their browser will remember the link including the keyword if they start typing.
