### ISSUE TITLE
Installation not removing install directory and no warning

### ISSUE THREAD

**Issue by JAY6390** [arastta/arastta#7]
Upon initial installation, I seemed to go round in circles. I'd complete the installation and would complete successfully click on the admin/catalog links on the success page and be taken back to the installation screen.

I thought this was a cached redirect initially, but it wasn't. Config file was complete and database had the tables and content added. It wasn't until I dug into the code that I discovered the line that will go to the installation directory if it exists automatically in `define.php`, regardless of the config being set up. Would be useful if there was a check that notified you to remove the directory if the config file is present and has data. I also noticed that I could reinstall the database with the same table prefix multiple times. Not sure if that is actually rewriting the content or not but surely it shouldn't allow it if the tables exist

**Comment by denisdulici** [comment]
Strange. Normally the install folder get deleted automatically at the last step. Was this a web or local install? What about the file/folder permissions of the install folder?

But in any case, if config.php exists, a warning should show up instead of redirect to installation.

The prefix is randomly generated each time you refresh the installation page. I tried to install with the same prefix and it gave me the "duplicate entry" error. Must check/improve this point too.

**Comment by JAY6390** [comment]
Was an pretty standard nginx/php/mysql stack on a local virtual machine (running ubuntu server through VMWare on the latest OSX). Permissions were maxed out to 777 and haven't had an issue with deletion of anything else to be honest. Took the prefix into account when I installed. I set it to `a_` manually each time. I also find the random prefixing a little unusual too. Not seen any FOSS do that before. Generally it's the software acronym (`wp_`, `oc_` etc). Might be worth looking at adding a bootstrap grouped button next to the field for those that want to generate a random one, as I can't see it being all that useful to the majority of users

**Comment by denisdulici** [comment]
Joomla uses random prefix for security purpose. WP users are always [recommended](https://yoast.com/articles/wordpress-security) to replace it.

You can easily take down a WP site when an SQLi shows up. But with Joomla, you need to know the prefix first which means already having that site in your hands ;)

**Comment by JAY6390** [comment]
Interesting. Hadn't seen that before, but from what you've described I can see the logic behind it

**Comment by osworx** [comment]
Joomla! for example is using random prefixes since 2.x
This is where Denis took that idea.
And I find it not that bad.
Should be also used at least for the admin password - with manually override if the installing person will not use that (would be only 2 lines more of code but finally for beginners a great benefit).

**Comment by JAY6390** [comment]
Traced the problem causing the originally discussed issue. It's this line
https://github.com/arastta/arastta/blob/master/install/model/main.php#L238
Basically my web server is neither the owner or the group of the installation directory, and so this actually lowered the permissions from 777 to 755 which means it doesn't delete the files. At the very least I would expect 775 for these permissions, not 755 which assumes that the file owner is the web server user. That's quite often not the case

**Comment by denisdulici** [comment]
Hmm.. even that code doesn't chmod the install folder?

I remember that it was attempted by OpenCart too but was not able to find it at the moment. Do you know that @JAY6390 ?

**Comment by JAY6390** [comment]
Hi Denis

The issue is that it _does_ chmod it. I set the install directory to `0777` originally, but that line of code will change it to `0755`. Since that then makes it non-writable for 'other' users (ie www-data for nginx in my case, where the owner and group are not www-data) it doesn't delete. I tried again with that line commented out (and reset the permissions to 777) and it deleted it as it should have.

Kind regards
Jay

**Comment by denisdulici** [comment]
Hi Jay,

Thanks for your intensive test, appreciated.

Will do further tests with that part totally removed and if no problem, just delete it.

Regards

**Comment by JAY6390** [comment]
OK, so ignoring most of what I said previously, this is not due to permissions on the install directory. It's actually a bigger issue with the Symfony filesystem method and it throwing exceptions that aren't being caught. Here's what my error log gave

```
2015/05/22 00:54:49 [error] 1085#0: *6 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Symfony\Component\Filesystem\Exception\IOException' with message 'Failed to chmod file "/var/www/html/arastta2/image/no_image.png".' in /var/www/html/arastta2/system/vendor/symfony/filesystem/Symfony/Component/Filesystem/Filesystem.php:196
Stack trace:
#0 /var/www/html/arastta2/system/vendor/symfony/filesystem/Symfony/Component/Filesystem/Filesystem.php(193): Symfony\Component\Filesystem\Filesystem->chmod(Object(FilesystemIterator), 493, 0, true)
#1 /var/www/html/arastta2/install/model/main.php(239): Symfony\Component\Filesystem\Filesystem->chmod(Array, 493, 0, true)
#2 /var/www/html/arastta2/install/controller/main.php(170): ModelMain->removeInstall()
#3 [internal function]: ControllerMain->removeInstall(Array)
#4 /var/www/html/arastta2/system/engine/action.php(73): call_user_func(Array, Array)
#5 /var/www/html/arastta2/system/engine/front.php(42): Action->execute(Object(Registry))
#6 /var/www/html/arastta2/system/engine/front.php(37): Front->execute(Obj" while reading response header from upstream, client: 192.168.1.50, server: ubuntu.local, request: "POST /arastta2/install/index.php?route=main/removeinstall HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "ubuntu.local", referrer: "http://ubuntu.local/arastta2/install/index.php"
```

I thought it odd that I didn't see this anywhere until I realised that arastta is using AJAX and the request is simply returning a 500 ISE. This explains why the system goes round in a loop and won't complete the install. It also means that the install directory not deleting is simply due to it being placed after this fatal error takes place. What is confusing is the fact that chmod is not possible on a file that has `777` permissions (the `image/no_image.png` file)

**Comment by denisdulici** [comment]
Strange thing... Though, added a workaround which discards chmod failure, can you please test it again?

**Comment by JAY6390** [comment]
Same issue I'm afraid - even the same error

```
2015/05/22 23:26:16 [error] 1085#0: *32 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Symfony\Component\Filesystem\Exception\IOException' with message 'Failed to chmod file "/var/www/html/arastta2/image/no_image.png".' in /var/www/html/arastta2/system/vendor/symfony/filesystem/Symfony/Component/Filesystem/Filesystem.php:196
Stack trace:
#0 /var/www/html/arastta2/system/vendor/symfony/filesystem/Symfony/Component/Filesystem/Filesystem.php(193): Symfony\Component\Filesystem\Filesystem->chmod(Object(FilesystemIterator), 493, 0, true)
#1 /var/www/html/arastta2/install/model/main.php(240): Symfony\Component\Filesystem\Filesystem->chmod(Array, 493, 0, true)
#2 /var/www/html/arastta2/install/controller/main.php(170): ModelMain->removeInstall()
#3 [internal function]: ControllerMain->removeInstall(Array)
#4 /var/www/html/arastta2/system/engine/action.php(73): call_user_func(Array, Array)
#5 /var/www/html/arastta2/system/engine/front.php(42): Action->execute(Object(Registry))
#6 /var/www/html/arastta2/system/engine/front.php(37): Front->execute(Obj" while reading response header from upstream, client: 192.168.1.50, server: ubuntu.local, request: "POST /arastta2/install/index.php?route=main/removeinstall HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "ubuntu.local", referrer: "http://ubuntu.local/arastta2/install/index.php"
```

**Comment by denisdulici** [comment]
Symfony exception catch doesn't work as per their [docs](http://symfony.com/doc/current/components/filesystem/introduction.html#error-handling) so I used the native PHP one in the new commit. It worked for throws from other methods such as rename. Can you please test again with installation?

**Comment by JAY6390** [comment]
:+1: It works!
