### ISSUE TITLE
False statement -> Future security updates will be applied automatically.

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#701]
This is something that I should have added long time ago, but never found it important enough ...
If this statement is important for the cloud service, it should be added in other ways only for those installs. For most others it's just a false statement, adding confusion.
![update_failed](https://cloud.githubusercontent.com/assets/858132/24955390/e567cbd0-1f8b-11e7-86ed-71ba3d6c42a7.png)

**Comment by denisdulici** [comment]
Technically that is possible with WordPress but not available in Arastta, yet. Should we add it?

**Comment by syntaxerror** [comment]
I would say no, because sometimes shit just happens. ;)

So I'm basically saying we're not ready for it, before the testing period is extended, and more testers is available.

If it's added now, it should be an optional **opt-in** setting, not a default setting.
