### ISSUE TITLE
Issue in Order status email

### ISSUE THREAD

**Issue by MajorPainage** [arastta/arastta#703]
Just a little issue with the default "Complete" order status email.

The following line needs fixing:

'Thank you for your interest in Arastta products. Your order has been received and will be processed once payment has been confirmed.'

Should be:

Thank you for your interest in {store} products. Your order has been received and will be processed once payment has been confirmed.

**Comment by syntaxerror** [comment]
True, all statuses except confirmed is OK (though it should be {store_name}'s):
https://github.com/arastta/arastta/blob/master/admin/language/en-GB/demo/email_template.php#L118

Anyhow, imho it should probably rather be:
`Thank you for your order, it has been received and will be processed as soon as possible.`

They have already ordered the stuff, so thanking for the interest doesn't make much sense. Also if online payment is used, the payment is already confirmed etc.
