### ISSUE TITLE
ERROR account/edit

### ISSUE THREAD

**Issue by djokerat** [arastta/arastta#708]
ERROR in account/edit

Parse error: syntax error, unexpected '[' in /home/webpage/system/vendor/volnix/csrf/src/CSRF.php on line 53 

Has someone else noticed this problem?

**Comment by denisdulici** [comment]
Which theme are you using?

**Comment by djokerat** [comment]
Second

**Comment by syntaxerror** [comment]
I simply get "Invalid CSRF token.", but that is on 'account/address/edit' - and no problems in 'account/edit' ...

There is no account overrides in the template used on updated sites, and it also happens on a fresh Norwegian demo installation using Second. No special characters used in form fields.

@djokerat what is filled into your form? Is it the same when using plain English characters?

_Removing 'account/address/edit' and 'account/edit' etc. from the CSRF protection list in the store settings is a possible workaround for now!_

**Comment by djokerat** [comment]
I installed a new copy, a demo environment ... after a user login and login ... edit an account

Parse error: syntax error, unexpected '[' in /home/demo_acccount/system/vendor/volnix/csrf/src/CSRF.php on line 53

**Comment by syntaxerror** [comment]
> @djokerat what is filled into your form? Is it the same when using plain English characters?

Also post your system info.

**Comment by djokerat** [comment]
The form is filled out when registering on the site. The error occurs when you try to edit. I tried with two language versions in both versions, gives an identical error.

System info:
Platform 	Arastta 1.6.1 Stable [ Tianjin ] 19-April-2017 15:30 GMT +3
PHP Version 	5.3.29
PHP Built On 	Linux mars.superhosting.bg 3.10.0-427.36.1.lve1.4.47.el7.x86_64 #1 SMP Sun May 7 18:31:43 EDT 2017 x86_64
Database Version 	5.5.52-cll
Database Collation 	cp1251_general_ci
Web Server 	Apache
Server Interface (SAPI) 	cgi-fcgi
User Agent 	Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by syntaxerror** [comment]
Yes, clearly it is. But WHAT do you fill into the form ...??

The error isn't normal, so you need to tell us if there is anything special filled into the form when you get the error.

But also, your PHP version is from the stone age, have you considered getting more modern hosting? It might help a lot, also when thinking security and speed: http://php.net/eol.php

**Comment by saymontio** [comment]
@syntaxerror I have to disagree with you.
The form of the address editing page does not contain the field for sending the token csrf.

On the demo server itself the error occurs. Attached image.

![arastta](https://user-images.githubusercontent.com/19983686/29467460-0ab54c88-8417-11e7-8cd9-164325a68c4c.jpg)

**Comment by saymontio** [comment]
821/5000
Due to the default of opencart in this route in question the validation made to evaluate if the file of the template and the same one of the route in question will not work because the route and the file are different, in this case or in others that the route is different Of the template path will give the CSRF invalid because the validation will not allow the CSRF to be inserted into the form. Generating a validation error so save it.

The solution that I found to map the routes together with their respective files, so that I did not have to concatenate the route but rather to get the route path and compare with the template that was passed as a parameter.

**Comment by syntaxerror** [comment]
I have also tested the demo without getting any error, so ...
https://github.com/arastta/arastta/issues/708#issuecomment-304531636
> Yes, clearly it is. **But WHAT do you fill into the form** ...??
>The error isn't normal, so you need to tell us if there is anything special filled into the form when you get the error.

Btw! What do you disagree with exactly? The URL on your screenshot is displaying that you're on 'account/address/edit', and not 'account/edit', exactly as I wrote ...
