### ISSUE TITLE
Blog - Some annoyances

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#710]
- On a multilingual site title is required in all languages. I think it's bad, t.ex. because most don't blog in several languages, at least not the same posts at the same time.
- Description isn't required at all, for any languages. A blog post with only title ...? ;)
- Category isn't required, but it really should. Anyhow it will display the category link icon on the blog post even if empty, and it's linking to 404 then.
- As mentioned before elsewhere, I don't like having blog settings in the site settings ...
![blog_home](https://cloud.githubusercontent.com/assets/858132/26521377/d394da9c-42ef-11e7-9b9d-4a760269b509.png)

**Comment by syntaxerror** [comment]
Image alignment i latest blog posts could be better in default/demo:
![blog_image](https://cloud.githubusercontent.com/assets/858132/26521977/2a0bce8a-42ff-11e7-8e20-cf32863977b9.png)

**Comment by syntaxerror** [comment]
Items row in category display is missing col-sm-xx, so the alignment gets wrong on items, and looks bad on templates using borders/background.

![blog_category](https://cloud.githubusercontent.com/assets/858132/26522084/6a973bae-4301-11e7-8c45-04f276dcd40d.png)

![blog_cat_item](https://cloud.githubusercontent.com/assets/858132/26522087/896e97d4-4301-11e7-9bd3-e58dc70fabd0.png)

**Comment by denisdulici** [comment]
Title and description can be overridden from view for the home. As for the category page, it's title and description is put there.

**Comment by syntaxerror** [comment]
> Title and description can be overridden from view for the home.

Not sure if I see what you mean here.
Any docs/screenshots displaying what you mean?

![blog_home](https://user-images.githubusercontent.com/858132/32394200-f99a7e36-c0e4-11e7-97b4-e33588c1fc42.png)

When it commes to this:
> Description isn't required at all, for any languages. A blog post with only title ...? ;)

It means you can add a blog post without any text, only title is required.
