### ISSUE TITLE
Blog - Image alignment

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#712]
Image alignment in could be better in Default/Second, especially in latest blog posts where it's extra visible, but also in list and blog view:

![blog_image](https://cloud.githubusercontent.com/assets/858132/26522135/37c1a5ce-4302-11e7-9ffd-a69409db7569.png)

**Comment by EnesErtugrul** [comment]
https://github.com/arastta/arastta/commit/cfb30dba38e51e51ea04fde54744df435a3219ef
