### ISSUE TITLE
Blog - Category display - Item row margin

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#713]
Items row/div in category display is missing col-xx-xx, so the alignment gets wrong on items, and looks bad on templates using borders/background.

![blog_category](https://cloud.githubusercontent.com/assets/858132/26522139/5da528b0-4302-11e7-91f6-eb5a26d9486e.png)

![blog_cat_item](https://cloud.githubusercontent.com/assets/858132/26522142/5f21dba2-4302-11e7-9b44-0e087003c1c6.png)

**Comment by EnesErtugrul** [comment]
https://github.com/arastta/arastta/commit/7659f7193062da997cfd30bf70ae3993c22ff1d6
