### ISSUE TITLE
Blog - Post Listing Settings

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#714]
The setting for 'Posts Per Row' doesn't seem to have any affect (using Second).
I tested changing it to 2, cleared cache, and it still display one post per row.

Same problem with 'Posts Per Page', and also for 'Posts Description Length'.

Setting for display of category is "missing", and this also applies to 'Post Page Settings'

![blog_items_row](https://cloud.githubusercontent.com/assets/858132/26522214/046e161a-4304-11e7-979d-6cfa16eb02fb.png)

![blog_list](https://cloud.githubusercontent.com/assets/858132/26522257/154ac054-4305-11e7-8b2b-7daad872c0f4.png)

**Comment by denisdulici** [comment]
**Posts Per Page**: works fine for me
**Posts Description Length**: fixed
**Posts Per Row**: removed as not used in themes
