### ISSUE TITLE
Postcode always required

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#716]
Postcode is always required in several browsers, displaying the browsers text like "Please fill this field".
It seems to be caused by a hard-coded "required" tag in both "default" and "second" template.

https://github.com/arastta/arastta/blob/master/catalog/view/theme/default/template/account/register.tpl#l276
https://github.com/arastta/arastta/blob/master/catalog/view/theme/second/template/account/register.tpl#l281

Note! This is in register account form, but also other forms should be checked to ensure they don't have the same bug.

![required_postcode](https://cloud.githubusercontent.com/assets/858132/26802298/b76d5942-4a48-11e7-9717-7d05e68e4d9a.png)

**Comment by EnesErtugrul** [comment]
Confirmed, will be fixed in the next version.
Thanks...

**Comment by syntaxerror** [comment]
Regarding the fix, is it any point in leaving the hard-coded "required" tag in the mentioned lines?
