### ISSUE TITLE
Missing search bar on Second theme on mobile device

### ISSUE THREAD

**Issue by MajorPainage** [arastta/arastta#717]
When viewing the website using Second theme on a PC, the search bar is where it should be.
When viewing the website using Second theme on a mobile device, the search bar is missing.

**Comment by cuneytsenturk** [comment]
if you click menu item you can show menu end.
![second-mobile](https://user-images.githubusercontent.com/10936547/35185330-03c76a92-fe14-11e7-9848-0a1c4f4b9993.png)
