### ISSUE TITLE
İletişim formuna captha eklenmeli.

### ISSUE THREAD

**Issue by mekamak** [arastta/arastta#719]
İletişim formuna captha eklenmeli.
İleriki zamanlarda spam gönderilere maruz kalınabilir.

**Comment by syntaxerror** [comment]
The project language is English, so please write in English if you post a issue.
If you don't write English, please use the appropriate forum instead: https://arastta.org/forum/categories/listings/turkish

**Comment by mekamak** [comment]
A captcha must be attached to the contact form.
In the future, spam may be exposed.

**Comment by syntaxerror** [comment]
It's not a issue, it's already there, if activated - and supported by the template.
Please make yourself familiar with the documentation section: https://arastta.org/docs/user-manual/extensions/captcha

You can see it live in the demo: http://demo.arastta.org/en/information/contact

Note! GitHub Issues is for "confirmed" issues, not support. Better use the forum if unsure.

**Comment by mekamak** [comment]
Thanks
