### ISSUE TITLE
Arastta servers is down, and admin doesn't work

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#738]
Arastta servers is down on it's second day, and people can not access their stores admin?

Why, what is this? It should not be so that the stores are reliable on the Arastta servers to log in and handle their orders etc.

**Comment by djokerat** [comment]
no access :(

**Comment by cuneytsenturk** [comment]
We're working on this issue, sorry for the inconvenience.

**Comment by syntaxerror** [comment]
Glad to see you online and working on it, hopefully it doesn't take long.

Still, when the servers are fixed, this issue in admin has to be fixed. It must be possible to login to the stores admin even if the system can't connect to Arastta servers.

I'm still looking at it, but I guess it's caused by the update check, at this point.

**Comment by djokerat** [comment]
The error that is generated is that the system is trying to connect to external resource http://arastta.io/core/1.0/version/1.6.2/5.3.29/5.5.54-cll/bg/4, which however unfortunately currently unavailable - can not be loaded.

**Comment by syntaxerror** [comment]
Thanks, it's coming from the getVersions function here: 
https://github.com/arastta/arastta/blob/master/admin/model/common/update.php#L206-L233

**Comment by djokerat** [comment]
As a temporary solution, I use this file to replace: 
admin / model / common
[update.zip](https://github.com/arastta/arastta/files/1509286/update.zip)

**Comment by cuneytsenturk** [comment]
You can comment these lines in the meantime:

https://github.com/arastta/arastta/blob/master/admin/model/common/update.php#L210-L233

**Comment by cuneytsenturk** [comment]
You can comment this line in the meantime:

https://github.com/arastta/arastta/blob/master/admin/model/common/update.php#L210-L233

**Comment by denisdulici** [comment]
Our server is up and running now, we're sorry for this inconvenience.
