### ISSUE TITLE
Arastta servers down, or access blocked - Admin doesn't work

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#740]
Adding this since #738 was closed.

Store owners don't get access to their admin section if Arastta servers are down, or access is blocked for some reason. T.ex. because of network or firewall issue, or disabled cURL etc.

This is caused by the getVersions function (update checking):
https://github.com/arastta/arastta/blob/master/admin/model/common/update.php#L206-L233

I've even seen reports in the forum about people even being unable to install Arastta, if their server doesn't get access to Arastta.io

One related issue is #730 

But there's also another issue when server is available, but the script is broken, or versions being unavailable for some reason. Then the update check will tell you there is new releases, with version numbers as 0.0.0. This should probably also be improved to skip showing anything if versions is unavailable, or rather display a message telling to check manually.

**Comment by denisdulici** [comment]
Tagged this for 1.7 version.
