### ISSUE TITLE
Migrate to laravel

### ISSUE THREAD

**Issue by aliqasemzadeh** [arastta/arastta#741]
Hello,
I think it would be good idea that we have plan to migrate to laravel.

**Comment by denisdulici** [comment]
That sounds good but requires a decent number of devs to write code. Let's see what we have. Who is in?

**Comment by syntaxerror** [comment]
I haven't looked at Laravel at all, and also don't have to much time to spend to write this amount of code from "scratch".

But another option could be to make it a sponsored project too ...

**Comment by denisdulici** [comment]
So no one else?
