### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by pmjcreations** [arastta/arastta#742]
I have fresh installed Arastta via Softaculous, and I am getting ERR_TOO_MANY_REDIRECTS for both admin and store URL

**Comment by syntaxerror** [comment]
This isn't something you should post here, unless you have debugged and confirmed it to be a generic issue. Use the support forum instead: https://arastta.org/forum

Anyhow, if it's true that it's a fresh untouched install from Softaculous (which I honestly doubt), you should actually talk with your host about it.

**Comment by pmjcreations** [comment]
Thank you @syntaxerror,  
Created a new stream. I will close this issue.
