### ISSUE TITLE
Multiple marketplace and installer fails

### ISSUE THREAD

**Issue by humantex** [arastta/arastta#743]
I've had multiple issues on a fresh code install to a local dev server...

SSL exceptions occurred for every subdomain involved with arastta.pro. Your cert expired on Friday, so I added individual cert exceptions to try to get registered as a user and finish installing and getting a basic setup. I finally got registered and logged in via the arastta site instead, since registering via admin failed. That was the only way to get past the first hurdle- just to get an API key, so that I could log back in to continue via the admin.

Admin marketplace failed to install anything. I tried the simplest/free extensions necessary (for me, anyway)... UPS, USPS, and FedEx + Amazon payments. No actions followed after clicking the '+install' buttons. Debugging was on as well as error logging. No errors were logged or visible in debug after several trys.

2nd set of attempts...
After locating the installer within admin and downloading all of the extensions (plus FraudLabs as it wasn't shown in the marketplace within admin). I tried several installs for each one. Every attempt showed a successful upload and install with a completed progress bar - but - the 'continue' button was inactive, and none of the extensions showed up as actually installed. No amount of refreshing/clearing/deleting any cache made any difference whatsoever. Again, no errors or meaningful debug messages anywhere in sight with a 'manual' install for any of them.

I assume it did, but I have no idea if the cert issue had any impact on the installation problems, but the only quasi-install I could complete were the internal ' installs' and enabling the built-in pay/ship extensions. Unfortunately they are simply not enough to provide the basics needed for me to run a shop.

For reference:
dev server / stack and versions...
Windows 7 64bit
Apache/2.4.25 (Win32) OpenSSL/1.0.2j
PHP/5.6.30
MySQL 5.6.35
Installed using: FireFox Dev edition, 58.0b13 (64-bit)

![arastta_cert-error](https://user-images.githubusercontent.com/16087649/34646072-e9084c86-f32c-11e7-8922-b4413b9dc28f.jpg)

![arastta_cert-error_2](https://user-images.githubusercontent.com/16087649/34646122-f163d8a4-f32d-11e7-92f0-fd0399e084eb.jpg)

**Comment by denisdulici** [comment]
This has been fixed.
