### ISSUE TITLE
Adding customer from admin - Wrong login URL in mail

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#744]
When adding customers from admin, they get mails containing a non working URL, as it's pointing to the admin folder.

Tested and confirmed on a fresh 1.6.2 running on PHP 7.0.27 (cgi-fcgi).

![customer_admin_url](https://user-images.githubusercontent.com/858132/34906657-598ae7fa-f87a-11e7-9264-00afec94af39.png)

_And as a side note/issue: It's also kind of useless on a Multi Store setup, as you have to login to the main store (because of issue #561), and the customer then gets the name and URL to this, instead of the preferred/intended store._

**Comment by denisdulici** [comment]
Can you please replace `getCustomerReplace ` method with the following one:

https://github.com/arastta/arastta/blob/master/system/library/emailtemplate.php#L240

```php
    public function getCustomerReplace($data)
    {
        $admin_folder = str_replace(DIR_ROOT, '', DIR_ADMIN);
        
        $account_href = str_replace($admin_folder, '', $this->url->link('account/login', '', 'SSL'));
        $activate_href = str_replace($admin_folder, '', $this->url->link('account/activate', 'passkey=' . $data['confirm_code'], 'SSL'));
        
        $result = array(
            'store_logo'     => $this->storeLogo(),
            'firstname'      => $data['firstname'],
            'lastname'       => $data['lastname'],
            'credit'         => isset($data['credit']) ? $data['credit'] : '0',
            'received_credit'=> isset($data['received_credit']) ? $data['received_credit'] : '0',
            'total_credit'   => isset($data['total_credit']) ? $data['total_credit'] : '0',
            'date'           => date($this->language->get('date_format_short'), strtotime(date("Y-m-d H:i:s"))),
            'store_name'     => $this->config->get('config_name'),
            'email'          => $data['email'],
            'password'       => $data['password'],
            'account_href'   => $account_href,
            'activate_href'  => (!empty($data['confirm_code'])) ? $activate_href : ''
        );

        return $result;
    }
```

**Comment by syntaxerror** [comment]
Thanks Denis,

Tested it on registration from both admin and store, and both works fine as fare as I can see.
