### ISSUE TITLE
Türkçe dil paketini nereden edinebilirim?

### ISSUE THREAD

**Issue by cnhsn** [arastta/arastta#746]
Türkçe dil paketini nereden edinebilirim?

**Comment by mekamak** [comment]
Kurarken Türkçe seçin. Kurduktan sonraysa eklentilerden  seçip ekleyebilirsiniz

**Comment by cuneytsenturk** [comment]
Kurulum sırasında **Türkçe** dilini seçe bileceğiniz gibi, 
[Burdan](https://translations.arastta.pro/europe/t%C3%BCrk%C3%A7e-tr-tr) indirip kurabilir veya  **Marketplace > Translations** menüsü altından **Türkçe** diline gidip  kurabilirsiniz.
