### ISSUE TITLE
Test pushed to core

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#751]
https://github.com/arastta/arastta/commit/f12f54ee887274832ce61ac124a07694eb105f38#diff-62d1fa90c8c77e28cd4b4e6635b9dac8R219

**Comment by denisdulici** [comment]
Was fixed later https://github.com/arastta/arastta/blob/1.7-dev/admin/model/common/update.php#L278

**Comment by syntaxerror** [comment]
Actually that is a different line and function Denis, the test is still there:
https://github.com/arastta/arastta/blob/1.7-dev/admin/model/common/update.php#L219
