### ISSUE TITLE
Contributions - Locale Git issue

### ISSUE THREAD

**Issue by syntaxerror** [arastta/arastta#758]
I still would like to contribute with code, but as the issue posted in developer team in august is still ignored, that is kind of hard to do ... minor changes can be done online, but not bigger ones.

---
I updated my local clone of latest Arastta Git, **in Linux**, and it showed changes after I pushed it.

So then I made a new clone, not pushing or doing anything than refreshing the folder display, and it also displays changes - related to the latest commit: https://github.com/arastta/arastta/commit/a309455087cffd65b7ab94f8b5e90af0c3b95cee

The local diff tool shows that the files are identical though.

It's all seems related to one strange line change (**line 3** on attached image, line 24/25 is also bad, but it's not the contribution stopper). bg (Bulgarian) files are fine, but the rest is messed up:
![index](https://user-images.githubusercontent.com/858132/37585039-5f0e8466-2b60-11e8-8821-185e22804e05.png)

Also tested on Mac, same issue there.

Using Windows and the "convert" option for line endings seems to eliminates the problem, but I can/will not work in Windows anyway, just have a virtual test machine.

Please check/correct line endings in those files, so we can work on the repo's again.

**Comment by cuneytsenturk** [comment]
I just cloned the 1.7-dev branch but was not able to reproduce your problem. On which branch are you working?

**Comment by syntaxerror** [comment]
Just tested once more on 1.7-dev, same result, on Linux.

Remember that you'll probably not see it on Windows, as it's a Linux/Unix issue. I see that part is missing here, sorry, but was mentioned initially in the developer team.

You probably tested it on Windows? That would normally not display it.

Note! I think maybe it can be some kind of mixed line endings in those. Ensuring they are using Unix line endings (re-saving as so), and then update git repo, would probably solve it.

**Comment by denisdulici** [comment]
Would appreciate a pull request from Linux users that solves this problem.

**Comment by syntaxerror** [comment]
Same problem on Mac.
As it was a PR from @cuneytsenturk breaking it, maybe it would be good to investigate what happened there, comparing the files before and after.
