### ISSUE TITLE
Anytime check updates module fails, whole admin panel fails

### ISSUE THREAD

**Issue by TaylanQ** [arastta/arastta#759]
Whenever an admin logins, system tries to check updates. And when the update server(arastta.io) shits, whole admin panel being unaccessible.

Come on man, don't treat this project as a step child :)

I changed the countUpdates function in this file for a temporary solution:
/admin/model/common/update.php

**Comment by denisdulici** [comment]
https://github.com/arastta/arastta/issues/740
