### ISSUE TITLE
Professional Copywriter Willing To Contribute

### ISSUE THREAD

**Issue by order4adwriter** [arastta/arastta#764]
I've seen  the demo of your eCommerce/shopping cart  app Arastta, on  your website... and I must say that it looks pretty cool!

I am a professional copywriter and I 'd like to contribute to your repository by writing compelling and informative content , especially for the [Arastta website's](arastta.org) Privacy Policy, Help/FAQ, Terms Of Use, Case Studies, Blog posts ... and other necessary marketing content needed on  the app and website.

My question is .... would you merge them into your repository when it's all done?

Please let me know so I can get started as soon as possible.

Thanks.

**Comment by denisdulici** [comment]
Thanks but the website content is not available on GitHub.

**Comment by order4adwriter** [comment]
Thanks for the reply.

That's ok... 

I can still create the content, send them as pull requests here for you to merge into the repository...later on at any time of your preference, you can create the pages, simply copy and paste each content into the respective page within the website.

I believe we can work that way...right?
