### ISSUE TITLE
arastta admin panel login not working

### ISSUE THREAD

**Issue by stbolen** [arastta/arastta#784]
arastta servers do not work and the system gives the following error when entering the arastta admin panel. 

Fatal error: Uncaught exception 'Httpful\Exception\ConnectionErrorException' with message 'Unable to connect to "http://arastta.io/core/1.0/version/1.6.2/5.5.38/5.5.5-10.1.44-MariaDB/tr/1": 6 Could not resolve host: arastta.io; Unknown error' in /home/domain.com/public_html/system/vendor/nategood/httpful/src/Httpful/Request.php:1028 Stack trace: #0 /home/domain.com/public_html/system/vendor/nategood/httpful/src/Httpful/Request.php(204): Httpful\Request->buildResponse(false) #1 /home/domain.com/public_html/admin/model/common/update.php(242): Httpful\Request->send() #2 /home/domain.com/public_html/admin/model/common/update.php(219): ModelCommonUpdate->getRemoteVersion('http://arastta....') #3 /home/domain.com/public_html/admin/model/common/update.php(172): ModelCommonUpdate->getVersions(Array) #4 /home/domain.com/public_html/admin/model/common/update.php(158): ModelCommonUpdate->getUpdates() #5 /home/domain.com/public_html/admin/controller/common/header.php(152): ModelCommonUpdate-> in /home/domain.com/public_html/system/vendor/nategood/httpful/src/Httpful/Request.php on line 1028

how can i solve it.

**Comment by syntaxerror** [comment]
Ref https://github.com/arastta/arastta/issues/738
Comment or remove line 210 to 233 in admin/model/common/update.php
https://github.com/arastta/arastta/blob/master/admin/model/common/update.php#L210-L233

Or you can also update manually to the **unsupported** developer release I made available here, **on your own risk and responsibility**: https://github.com/syntaxerror/arastta/releases/tag/1.7.0-dev

Pay attention to the database change: https://github.com/arastta/arastta/blob/1.7-dev/install/update.php#L931-L934

**Comment by stbolen** [comment]
thanks for your answer. worked.
