### ISSUE TITLE
Admin side menu not scrolling after collapse view

### ISSUE THREAD

**Issue by ysmnikhil** [arastta/arastta#8]
Features are awesome in Arastta :)

issue is small but will create problem in small devices.
- https://nimbus.everhelper.me/client/notes/share/218432/w1gsTaRPmcrstqu97b05OxB40vqensBb/
- in small devices collapse view is always stored to collapsed menu after click any link (may be local storage issue).
- I have to say your file manager feature is awesome :) but these issue solution will make it better 
  https://nimbus.everhelper.me/client/notes/share/218440/MCG5wzLlwFLAyM4pQQBEMIK1qHZCegNB/
  after fullscreen header is hiding code.

**Comment by denisdulici** [comment]
Glad you liked them @Nikhil-7 

Lets see @cuneytsenturk can do about these issues
